// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlDev.Data;

#nullable disable

namespace DevSqlServer.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlDev.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Address1 = "629 Muller Ridges",
                            City = "East Orie",
                            PostalCode = "08923",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 52,
                            Address1 = "1721 Gusikowski Trace",
                            Address2 = "Suite 738",
                            City = "Port Eusebio",
                            PostalCode = "49249",
                            StateProvince = "Wisconsin"
                        },
                        new
                        {
                            Id = 53,
                            Address1 = "51423 Adelle Rest",
                            City = "Jastburgh",
                            PostalCode = "50403",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 54,
                            Address1 = "300 Rath Station",
                            Address2 = "Suite 177",
                            City = "Jonathanfort",
                            PostalCode = "41319",
                            StateProvince = "Indiana"
                        },
                        new
                        {
                            Id = 55,
                            Address1 = "2406 Lydia Meadow",
                            City = "Kilbacktown",
                            PostalCode = "82606-7232",
                            StateProvince = "Nebraska"
                        },
                        new
                        {
                            Id = 56,
                            Address1 = "72277 Weber Flat",
                            City = "North Eliane",
                            PostalCode = "56363-3794",
                            StateProvince = "New Mexico"
                        },
                        new
                        {
                            Id = 57,
                            Address1 = "065 Salma Crossing",
                            Address2 = "Suite 019",
                            City = "Evashire",
                            PostalCode = "26754",
                            StateProvince = "Delaware"
                        },
                        new
                        {
                            Id = 58,
                            Address1 = "259 Jacobs Ramp",
                            Address2 = "Suite 383",
                            City = "Port Fabiola",
                            PostalCode = "73246",
                            StateProvince = "West Virginia"
                        },
                        new
                        {
                            Id = 59,
                            Address1 = "953 Madison Forges",
                            City = "New Whitney",
                            PostalCode = "12673",
                            StateProvince = "Idaho"
                        },
                        new
                        {
                            Id = 60,
                            Address1 = "2921 Alberto Green",
                            Address2 = "Apt. 084",
                            City = "Edgarshire",
                            PostalCode = "14268-9235",
                            StateProvince = "Mississippi"
                        },
                        new
                        {
                            Id = 61,
                            Address1 = "54009 Arch Freeway",
                            City = "Port Kaitlin",
                            PostalCode = "69176",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 62,
                            Address1 = "008 Waino Gateway",
                            City = "Vestaville",
                            PostalCode = "02847",
                            StateProvince = "New Mexico"
                        },
                        new
                        {
                            Id = 63,
                            Address1 = "09184 Koch Club",
                            City = "Torphyville",
                            PostalCode = "61499",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 64,
                            Address1 = "57023 Reichert Crest",
                            Address2 = "Suite 359",
                            City = "Port Dock",
                            PostalCode = "84054-1061",
                            StateProvince = "New Mexico"
                        },
                        new
                        {
                            Id = 65,
                            Address1 = "899 Upton Loop",
                            Address2 = "Apt. 796",
                            City = "Lake Eliezer",
                            PostalCode = "24879",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 66,
                            Address1 = "4394 Rachael Course",
                            Address2 = "Apt. 916",
                            City = "North Arden",
                            PostalCode = "45781",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 67,
                            Address1 = "82338 Adelbert Terrace",
                            Address2 = "Suite 520",
                            City = "Cartermouth",
                            PostalCode = "71139-2153",
                            StateProvince = "Mississippi"
                        },
                        new
                        {
                            Id = 68,
                            Address1 = "6813 Judy Brooks",
                            Address2 = "Apt. 685",
                            City = "Willardshire",
                            PostalCode = "09272",
                            StateProvince = "South Dakota"
                        },
                        new
                        {
                            Id = 69,
                            Address1 = "0667 Anthony Valleys",
                            Address2 = "Suite 048",
                            City = "West Virgil",
                            PostalCode = "68713-4393",
                            StateProvince = "Louisiana"
                        },
                        new
                        {
                            Id = 70,
                            Address1 = "8266 Ashley Plains",
                            Address2 = "Suite 224",
                            City = "New Mckaylaburgh",
                            PostalCode = "56163",
                            StateProvince = "Colorado"
                        },
                        new
                        {
                            Id = 71,
                            Address1 = "6512 Daniela Plains",
                            Address2 = "Apt. 359",
                            City = "Lake Louveniachester",
                            PostalCode = "61875",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 72,
                            Address1 = "53875 Theodora Summit",
                            City = "Alyceberg",
                            PostalCode = "07402-9994",
                            StateProvince = "Missouri"
                        },
                        new
                        {
                            Id = 73,
                            Address1 = "943 Sawayn Rest",
                            Address2 = "Apt. 499",
                            City = "West Kendrick",
                            PostalCode = "60469",
                            StateProvince = "West Virginia"
                        },
                        new
                        {
                            Id = 74,
                            Address1 = "169 Trisha Route",
                            Address2 = "Suite 339",
                            City = "Wuckertchester",
                            PostalCode = "38857-3405",
                            StateProvince = "California"
                        },
                        new
                        {
                            Id = 75,
                            Address1 = "191 Shaylee Cliffs",
                            City = "Jammiebury",
                            PostalCode = "27695",
                            StateProvince = "New Jersey"
                        },
                        new
                        {
                            Id = 76,
                            Address1 = "8104 Pinkie Divide",
                            City = "Daphneyhaven",
                            PostalCode = "14092-2312",
                            StateProvince = "Ohio"
                        },
                        new
                        {
                            Id = 77,
                            Address1 = "16503 Sammie Inlet",
                            Address2 = "Suite 371",
                            City = "South Eldonville",
                            PostalCode = "14098",
                            StateProvince = "Wyoming"
                        },
                        new
                        {
                            Id = 78,
                            Address1 = "8791 Reyna Pine",
                            City = "Addieville",
                            PostalCode = "44257-6911",
                            StateProvince = "Nebraska"
                        },
                        new
                        {
                            Id = 79,
                            Address1 = "501 Heaney View",
                            Address2 = "Apt. 279",
                            City = "Bahringerburgh",
                            PostalCode = "31200-9144",
                            StateProvince = "Utah"
                        },
                        new
                        {
                            Id = 80,
                            Address1 = "658 Conn Rapids",
                            City = "New Westonshire",
                            PostalCode = "86229-9508",
                            StateProvince = "South Dakota"
                        },
                        new
                        {
                            Id = 81,
                            Address1 = "032 Ernser Lights",
                            Address2 = "Apt. 002",
                            City = "Morissettemouth",
                            PostalCode = "80600-1167",
                            StateProvince = "Wisconsin"
                        },
                        new
                        {
                            Id = 82,
                            Address1 = "6676 Emmerich Courts",
                            Address2 = "Suite 633",
                            City = "New Sylvan",
                            PostalCode = "87659-9792",
                            StateProvince = "Rhode Island"
                        },
                        new
                        {
                            Id = 83,
                            Address1 = "375 Bergnaum Squares",
                            City = "Port Breannaburgh",
                            PostalCode = "32413",
                            StateProvince = "Nevada"
                        },
                        new
                        {
                            Id = 84,
                            Address1 = "824 Sabina Curve",
                            Address2 = "Suite 479",
                            City = "Laishaton",
                            PostalCode = "00805-5736",
                            StateProvince = "Washington"
                        },
                        new
                        {
                            Id = 85,
                            Address1 = "64502 Weissnat Mount",
                            Address2 = "Suite 476",
                            City = "Schulistbury",
                            PostalCode = "69444",
                            StateProvince = "Wyoming"
                        },
                        new
                        {
                            Id = 86,
                            Address1 = "41718 Keeling Drive",
                            City = "North Kaycee",
                            PostalCode = "43430",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 87,
                            Address1 = "48241 Champlin Bypass",
                            Address2 = "Suite 918",
                            City = "Nadermouth",
                            PostalCode = "92168",
                            StateProvince = "South Dakota"
                        },
                        new
                        {
                            Id = 88,
                            Address1 = "9613 Huels Brook",
                            City = "West Rico",
                            PostalCode = "85869",
                            StateProvince = "Alaska"
                        },
                        new
                        {
                            Id = 89,
                            Address1 = "140 Mueller Vista",
                            City = "Kozeyville",
                            PostalCode = "84439-4490",
                            StateProvince = "Washington"
                        },
                        new
                        {
                            Id = 90,
                            Address1 = "76121 Gislason Rue",
                            City = "West Maurice",
                            PostalCode = "05988",
                            StateProvince = "Iowa"
                        },
                        new
                        {
                            Id = 91,
                            Address1 = "31902 Waelchi Station",
                            City = "Maraberg",
                            PostalCode = "46519-6717",
                            StateProvince = "Wyoming"
                        },
                        new
                        {
                            Id = 92,
                            Address1 = "641 Vincenza Lock",
                            City = "New Ernestoville",
                            PostalCode = "97339",
                            StateProvince = "Illinois"
                        },
                        new
                        {
                            Id = 93,
                            Address1 = "0169 Luna Lakes",
                            City = "Agustinahaven",
                            PostalCode = "82024",
                            StateProvince = "Maryland"
                        },
                        new
                        {
                            Id = 94,
                            Address1 = "207 Kassulke Route",
                            City = "Prosaccoberg",
                            PostalCode = "89104",
                            StateProvince = "Iowa"
                        },
                        new
                        {
                            Id = 95,
                            Address1 = "9478 Boyle Grove",
                            City = "Tremaynechester",
                            PostalCode = "27258",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 96,
                            Address1 = "123 Kellen Court",
                            Address2 = "Suite 377",
                            City = "Lake Rhiannonhaven",
                            PostalCode = "02109",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 97,
                            Address1 = "86611 Ralph Turnpike",
                            Address2 = "Apt. 679",
                            City = "Rolandofurt",
                            PostalCode = "49154",
                            StateProvince = "Texas"
                        },
                        new
                        {
                            Id = 98,
                            Address1 = "58629 Caleigh Meadows",
                            City = "Boscofurt",
                            PostalCode = "11973",
                            StateProvince = "Nevada"
                        },
                        new
                        {
                            Id = 99,
                            Address1 = "6963 Rosanna Manors",
                            Address2 = "Apt. 525",
                            City = "Derickshire",
                            PostalCode = "67328-4326",
                            StateProvince = "Mississippi"
                        },
                        new
                        {
                            Id = 100,
                            Address1 = "73057 Ferne Place",
                            City = "Langmouth",
                            PostalCode = "97160",
                            StateProvince = "Nevada"
                        });
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            AddressId = 51,
                            CompanyName = "Howe, Ortiz and Ritchie",
                            ContactName = "Vito Lehner",
                            Phone = "382-582-4764"
                        },
                        new
                        {
                            Id = 52,
                            AddressId = 52,
                            CompanyName = "Ankunding Group",
                            ContactName = "Tessie Braun",
                            Phone = "834-345-3323"
                        },
                        new
                        {
                            Id = 53,
                            AddressId = 53,
                            CompanyName = "Schimmel, Mayer and Douglas",
                            ContactName = "Telly Ratke",
                            Phone = "215-831-4391"
                        },
                        new
                        {
                            Id = 54,
                            AddressId = 54,
                            CompanyName = "Kovacek Group",
                            ContactName = "Emerson Heller",
                            Phone = "743-651-6040"
                        },
                        new
                        {
                            Id = 55,
                            AddressId = 55,
                            CompanyName = "Reichert Group",
                            ContactName = "Ashton Gerhold",
                            Phone = "991-675-5090"
                        },
                        new
                        {
                            Id = 56,
                            AddressId = 56,
                            CompanyName = "Bergstrom - Davis",
                            ContactName = "Ona Jacobson"
                        },
                        new
                        {
                            Id = 57,
                            AddressId = 57,
                            CompanyName = "Osinski Inc",
                            ContactName = "Madalyn Willms",
                            Phone = "229-201-5194"
                        },
                        new
                        {
                            Id = 58,
                            AddressId = 58,
                            CompanyName = "Okuneva - Goldner",
                            ContactName = "Zoe Haley"
                        },
                        new
                        {
                            Id = 59,
                            AddressId = 59,
                            CompanyName = "Jenkins, Feeney and Hegmann",
                            ContactName = "Reymundo Johnston",
                            Phone = "509-483-4890"
                        },
                        new
                        {
                            Id = 60,
                            AddressId = 60,
                            CompanyName = "Rolfson and Sons",
                            ContactName = "Selena Blick"
                        },
                        new
                        {
                            Id = 61,
                            AddressId = 61,
                            CompanyName = "Stoltenberg Group",
                            ContactName = "Nicklaus Boyle",
                            Phone = "619-294-4714"
                        },
                        new
                        {
                            Id = 62,
                            AddressId = 62,
                            CompanyName = "Fay, Crist and McClure",
                            ContactName = "Laurianne Champlin",
                            Phone = "717-730-4259"
                        },
                        new
                        {
                            Id = 63,
                            AddressId = 63,
                            CompanyName = "Harris Group",
                            ContactName = "Britney Hagenes",
                            Phone = "371-691-3672"
                        },
                        new
                        {
                            Id = 64,
                            AddressId = 64,
                            CompanyName = "Beer and Sons",
                            ContactName = "Penelope Bartell",
                            Phone = "621-263-1976"
                        },
                        new
                        {
                            Id = 65,
                            AddressId = 65,
                            CompanyName = "Davis - Maggio",
                            ContactName = "Rubye Kuhn",
                            Phone = "805-784-2524"
                        },
                        new
                        {
                            Id = 66,
                            AddressId = 66,
                            CompanyName = "Doyle and Sons",
                            ContactName = "Daphnee Friesen",
                            Phone = "363-379-7847"
                        },
                        new
                        {
                            Id = 67,
                            AddressId = 67,
                            CompanyName = "Pfannerstill Group",
                            ContactName = "Jermain Fay",
                            Phone = "523-522-1187"
                        },
                        new
                        {
                            Id = 68,
                            AddressId = 68,
                            CompanyName = "Hamill Inc",
                            ContactName = "Nathaniel Jakubowski",
                            Phone = "529-395-7891"
                        },
                        new
                        {
                            Id = 69,
                            AddressId = 69,
                            CompanyName = "Zieme Group",
                            ContactName = "Reymundo Haley",
                            Phone = "978-808-0905"
                        },
                        new
                        {
                            Id = 70,
                            AddressId = 70,
                            CompanyName = "Bosco LLC",
                            ContactName = "Kelley Hamill",
                            Phone = "285-265-3864"
                        },
                        new
                        {
                            Id = 71,
                            AddressId = 71,
                            CompanyName = "Blick Inc",
                            ContactName = "Bianka Towne",
                            Phone = "915-639-3513"
                        },
                        new
                        {
                            Id = 72,
                            AddressId = 72,
                            CompanyName = "Block - Raynor",
                            ContactName = "Nickolas Hilpert",
                            Phone = "609-813-6448"
                        },
                        new
                        {
                            Id = 73,
                            AddressId = 73,
                            CompanyName = "Jakubowski - Von",
                            ContactName = "Roy VonRueden",
                            Phone = "515-640-9162"
                        },
                        new
                        {
                            Id = 74,
                            AddressId = 74,
                            CompanyName = "Ledner Group",
                            ContactName = "Orie Walker"
                        },
                        new
                        {
                            Id = 75,
                            AddressId = 75,
                            CompanyName = "Roberts - Osinski",
                            ContactName = "Clark Gibson",
                            Phone = "694-252-9589"
                        },
                        new
                        {
                            Id = 76,
                            AddressId = 76,
                            CompanyName = "Ziemann, Hickle and Williamson",
                            ContactName = "Jadyn Bernier",
                            Phone = "434-268-2855"
                        },
                        new
                        {
                            Id = 77,
                            AddressId = 77,
                            CompanyName = "Jenkins, Hessel and Bailey",
                            ContactName = "Alycia Bergstrom",
                            Phone = "802-534-1930"
                        },
                        new
                        {
                            Id = 78,
                            AddressId = 78,
                            CompanyName = "Mayer, Lynch and Predovic",
                            ContactName = "Madison Koch"
                        },
                        new
                        {
                            Id = 79,
                            AddressId = 79,
                            CompanyName = "Kuhic, McDermott and Friesen",
                            ContactName = "Reina Ward",
                            Phone = "647-595-1527"
                        },
                        new
                        {
                            Id = 80,
                            AddressId = 80,
                            CompanyName = "Yundt, Balistreri and Botsford",
                            ContactName = "Darryl Wilderman"
                        },
                        new
                        {
                            Id = 81,
                            AddressId = 81,
                            CompanyName = "Steuber LLC",
                            ContactName = "Logan Botsford",
                            Phone = "712-965-0636"
                        },
                        new
                        {
                            Id = 82,
                            AddressId = 82,
                            CompanyName = "Schneider Inc",
                            ContactName = "Lorenza Bashirian",
                            Phone = "578-666-6291"
                        },
                        new
                        {
                            Id = 83,
                            AddressId = 83,
                            CompanyName = "Dickens, Haley and Johnston",
                            ContactName = "Devin Sanford",
                            Phone = "808-492-3259"
                        },
                        new
                        {
                            Id = 84,
                            AddressId = 84,
                            CompanyName = "Dibbert, Schaefer and Grant",
                            ContactName = "Beryl Wiza",
                            Phone = "787-449-3924"
                        },
                        new
                        {
                            Id = 85,
                            AddressId = 85,
                            CompanyName = "Koelpin Group",
                            ContactName = "Clementina Corwin",
                            Phone = "565-214-2350"
                        },
                        new
                        {
                            Id = 86,
                            AddressId = 86,
                            CompanyName = "Herzog - Schinner",
                            ContactName = "Hailie Haley",
                            Phone = "750-340-3369"
                        },
                        new
                        {
                            Id = 87,
                            AddressId = 87,
                            CompanyName = "Herman, Bergstrom and Bogisich",
                            ContactName = "Thalia Breitenberg",
                            Phone = "775-758-2041"
                        },
                        new
                        {
                            Id = 88,
                            AddressId = 88,
                            CompanyName = "Yost LLC",
                            ContactName = "Jarod Bergstrom",
                            Phone = "724-506-4629"
                        },
                        new
                        {
                            Id = 89,
                            AddressId = 89,
                            CompanyName = "Kilback, Baumbach and Lemke",
                            ContactName = "Yoshiko Stiedemann",
                            Phone = "306-772-3200"
                        },
                        new
                        {
                            Id = 90,
                            AddressId = 90,
                            CompanyName = "Fadel, Quigley and Gulgowski",
                            ContactName = "Daryl Ritchie",
                            Phone = "784-600-3026"
                        },
                        new
                        {
                            Id = 91,
                            AddressId = 91,
                            CompanyName = "Murazik - Hills",
                            ContactName = "Lenore Jacobs",
                            Phone = "494-749-2810"
                        },
                        new
                        {
                            Id = 92,
                            AddressId = 92,
                            CompanyName = "Rohan - Blanda",
                            ContactName = "Clotilde Walter",
                            Phone = "639-713-2675"
                        },
                        new
                        {
                            Id = 93,
                            AddressId = 93,
                            CompanyName = "Rutherford - Schamberger",
                            ContactName = "Gregory Padberg",
                            Phone = "499-638-3739"
                        },
                        new
                        {
                            Id = 94,
                            AddressId = 94,
                            CompanyName = "Hilll, Schiller and Hayes",
                            ContactName = "Damien Jenkins",
                            Phone = "790-962-9536"
                        },
                        new
                        {
                            Id = 95,
                            AddressId = 95,
                            CompanyName = "O'Conner - Borer",
                            ContactName = "Felipe Orn",
                            Phone = "921-326-7356"
                        },
                        new
                        {
                            Id = 96,
                            AddressId = 96,
                            CompanyName = "Grimes and Sons",
                            ContactName = "Vesta Douglas",
                            Phone = "308-346-6294"
                        },
                        new
                        {
                            Id = 97,
                            AddressId = 97,
                            CompanyName = "Johns and Sons",
                            ContactName = "Mallory Torphy",
                            Phone = "935-410-1025"
                        },
                        new
                        {
                            Id = 98,
                            AddressId = 98,
                            CompanyName = "Block Group",
                            ContactName = "Cordell Borer",
                            Phone = "734-795-1369"
                        },
                        new
                        {
                            Id = 99,
                            AddressId = 99,
                            CompanyName = "Nader, Lind and Wyman",
                            ContactName = "Elsa Wisozk",
                            Phone = "408-240-1005"
                        },
                        new
                        {
                            Id = 100,
                            AddressId = 100,
                            CompanyName = "Monahan Inc",
                            ContactName = "Anabelle Gerhold",
                            Phone = "979-528-4009"
                        });
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Customer", b =>
                {
                    b.HasOne("SqlDev.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Order", b =>
                {
                    b.HasOne("SqlDev.Data.Entities.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlDev.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("SqlDev.Data.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
