// <auto-generated />
using System;
using AddressBook.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressBook.Api.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressBook.Api.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookEntryId")
                        .HasColumnType("int");

                    b.Property<string>("CityTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookEntryId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            BookEntryId = 26,
                            CityTown = "South Daniela",
                            Country = "Qatar",
                            Line1 = "906 Corene Lodge",
                            Line2 = "Suite 210",
                            Line3 = "Suite 163",
                            Name = "Auto Loan Account modular",
                            PostalCode = "51243-5980",
                            StateProvince = "New York"
                        },
                        new
                        {
                            Id = 52,
                            BookEntryId = 26,
                            CityTown = "Alyceberg",
                            Country = "Reunion",
                            Line1 = "61298 Purdy Mountains",
                            Line2 = "Suite 387",
                            Line3 = "Apt. 740",
                            Name = "Credit Card Account yellow",
                            PostalCode = "07402-9994",
                            StateProvince = "Missouri"
                        },
                        new
                        {
                            Id = 53,
                            BookEntryId = 27,
                            CityTown = "Kiehnside",
                            Country = "Virgin Islands, U.S.",
                            Line1 = "9972 Dayna Knoll",
                            Line2 = "Apt. 592",
                            Line3 = "Apt. 469",
                            Name = "Customer synthesize",
                            PostalCode = "69633",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 54,
                            BookEntryId = 27,
                            CityTown = "Fritschtown",
                            Country = "Falkland Islands (Malvinas)",
                            Line1 = "5734 Quinton Stravenue",
                            Line3 = "Suite 019",
                            Name = "Personal Loan Account Developer",
                            PostalCode = "64354",
                            StateProvince = "Pennsylvania"
                        },
                        new
                        {
                            Id = 55,
                            BookEntryId = 28,
                            CityTown = "South Augustusside",
                            Country = "Haiti",
                            Line1 = "8104 Pinkie Divide",
                            Line3 = "Suite 286",
                            Name = "alarm Designer",
                            PostalCode = "31291",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 56,
                            BookEntryId = 28,
                            CityTown = "South Reyna",
                            Country = "Albania",
                            Line1 = "515 Meaghan Drive",
                            Line3 = "Apt. 098",
                            Name = "PCI Generic Granite Chair",
                            PostalCode = "79122-7917",
                            StateProvince = "New Jersey"
                        },
                        new
                        {
                            Id = 57,
                            BookEntryId = 29,
                            CityTown = "Noetown",
                            Country = "Isle of Man",
                            Line1 = "91117 Satterfield Rapids",
                            Line3 = "Apt. 027",
                            Name = "sky blue District",
                            PostalCode = "73120-0914",
                            StateProvince = "Indiana"
                        },
                        new
                        {
                            Id = 58,
                            BookEntryId = 29,
                            CityTown = "Port Theodora",
                            Country = "Jamaica",
                            Line1 = "598 Schuppe Knolls",
                            Line2 = "Apt. 059",
                            Line3 = "Suite 986",
                            Name = "reboot Belize Dollar",
                            PostalCode = "80782",
                            StateProvince = "New Hampshire"
                        },
                        new
                        {
                            Id = 59,
                            BookEntryId = 30,
                            CityTown = "Emmerichland",
                            Country = "Tunisia",
                            Line1 = "67998 Willy Views",
                            Line3 = "Apt. 675",
                            Name = "Incredible pink",
                            PostalCode = "76663-3736",
                            StateProvince = "New York"
                        },
                        new
                        {
                            Id = 60,
                            BookEntryId = 30,
                            CityTown = "East Uriah",
                            Country = "Botswana",
                            Line1 = "9297 Wunsch Road",
                            Line2 = "Suite 073",
                            Line3 = "Suite 589",
                            Name = "synthesize USB",
                            PostalCode = "54324",
                            StateProvince = "Connecticut"
                        },
                        new
                        {
                            Id = 61,
                            BookEntryId = 31,
                            CityTown = "Maymiebury",
                            Country = "Isle of Man",
                            Line1 = "64798 Feil Knoll",
                            Line2 = "Suite 509",
                            Line3 = "Apt. 080",
                            Name = "web-enabled back up",
                            PostalCode = "26956",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 62,
                            BookEntryId = 31,
                            CityTown = "South Carmelmouth",
                            Country = "Algeria",
                            Line1 = "839 Leffler Walk",
                            Line3 = "Apt. 305",
                            Name = "Burgs upward-trending",
                            PostalCode = "10523-4057",
                            StateProvince = "Florida"
                        },
                        new
                        {
                            Id = 63,
                            BookEntryId = 32,
                            CityTown = "Raphaelborough",
                            Country = "New Zealand",
                            Line1 = "048 Meagan Creek",
                            Line2 = "Apt. 415",
                            Line3 = "Apt. 877",
                            Name = "Isle Groves",
                            PostalCode = "16864",
                            StateProvince = "Virginia"
                        },
                        new
                        {
                            Id = 64,
                            BookEntryId = 32,
                            CityTown = "Muellershire",
                            Country = "Central African Republic",
                            Line1 = "6133 Evie Locks",
                            Line2 = "Suite 018",
                            Line3 = "Suite 692",
                            Name = "synergies Orchestrator",
                            PostalCode = "00340",
                            StateProvince = "Delaware"
                        },
                        new
                        {
                            Id = 65,
                            BookEntryId = 33,
                            CityTown = "East Sophiaborough",
                            Country = "United States of America",
                            Line1 = "4902 Zachariah Lane",
                            Line2 = "Apt. 827",
                            Name = "indexing Unbranded Metal Bacon",
                            PostalCode = "62205",
                            StateProvince = "Maryland"
                        },
                        new
                        {
                            Id = 66,
                            BookEntryId = 33,
                            CityTown = "Port Mariannachester",
                            Country = "Iran",
                            Line1 = "2920 Zetta Centers",
                            Line3 = "Suite 946",
                            Name = "SAS Intelligent Granite Sausages",
                            PostalCode = "06094-6412",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 67,
                            BookEntryId = 34,
                            CityTown = "Mayertside",
                            Country = "Ukraine",
                            Line1 = "97339 Dena Avenue",
                            Line3 = "Apt. 169",
                            Name = "program Customer-focused",
                            PostalCode = "08348-2024",
                            StateProvince = "Illinois"
                        },
                        new
                        {
                            Id = 68,
                            BookEntryId = 34,
                            CityTown = "Boyleburgh",
                            Country = "Nepal",
                            Line1 = "91287 Hessel Creek",
                            Line2 = "Apt. 218",
                            Line3 = "Apt. 049",
                            Name = "1080p mindshare",
                            PostalCode = "78097",
                            StateProvince = "Virginia"
                        },
                        new
                        {
                            Id = 69,
                            BookEntryId = 35,
                            CityTown = "Lake Rhiannonhaven",
                            Country = "Micronesia",
                            Line1 = "58961 Pearlie Forge",
                            Line3 = "Suite 377",
                            Name = "next generation Quality",
                            PostalCode = "02109",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 70,
                            BookEntryId = 35,
                            CityTown = "East Jeffrey",
                            Country = "Benin",
                            Line1 = "79678 Bernadine Plain",
                            Line2 = "Suite 824",
                            Line3 = "Apt. 544",
                            Name = "Intelligent Soft Salad generating",
                            PostalCode = "62999-4407",
                            StateProvince = "New Hampshire"
                        },
                        new
                        {
                            Id = 71,
                            BookEntryId = 36,
                            CityTown = "Port Maritza",
                            Country = "Niger",
                            Line1 = "8469 Kaylah Glens",
                            Line3 = "Suite 662",
                            Name = "payment Rustic Wooden Chips",
                            PostalCode = "28432",
                            StateProvince = "Rhode Island"
                        },
                        new
                        {
                            Id = 72,
                            BookEntryId = 36,
                            CityTown = "New Amariton",
                            Country = "Cayman Islands",
                            Line1 = "773 Aimee Overpass",
                            Line2 = "Suite 309",
                            Line3 = "Suite 509",
                            Name = "French Guiana forecast",
                            PostalCode = "34304-3101",
                            StateProvince = "New Jersey"
                        },
                        new
                        {
                            Id = 73,
                            BookEntryId = 37,
                            CityTown = "Ashleebury",
                            Country = "Benin",
                            Line1 = "43339 Mills Route",
                            Line3 = "Suite 351",
                            Name = "Auto Loan Account distributed",
                            PostalCode = "61973-9763",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 74,
                            BookEntryId = 37,
                            CityTown = "Bayleeburgh",
                            Country = "British Indian Ocean Territory (Chagos Archipelago)",
                            Line1 = "2164 Crooks Lodge",
                            Line2 = "Suite 581",
                            Line3 = "Suite 868",
                            Name = "Chief Isle",
                            PostalCode = "99053-6278",
                            StateProvince = "Louisiana"
                        },
                        new
                        {
                            Id = 75,
                            BookEntryId = 38,
                            CityTown = "East Jakob",
                            Country = "Palestinian Territory",
                            Line1 = "248 Rohan Circle",
                            Line3 = "Suite 728",
                            Name = "Shoes Chief",
                            PostalCode = "28670-9571",
                            StateProvince = "Florida"
                        },
                        new
                        {
                            Id = 76,
                            BookEntryId = 38,
                            CityTown = "Trudiebury",
                            Country = "Burundi",
                            Line1 = "86811 Jared Expressway",
                            Line2 = "Suite 081",
                            Line3 = "Apt. 742",
                            Name = "Dynamic Security",
                            PostalCode = "86138",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 77,
                            BookEntryId = 39,
                            CityTown = "Yostbury",
                            Country = "Palestinian Territory",
                            Line1 = "64991 Alexa Isle",
                            Line3 = "Apt. 835",
                            Name = "gold Fantastic Fresh Computer",
                            PostalCode = "53062",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 78,
                            BookEntryId = 39,
                            CityTown = "Faheymouth",
                            Country = "Niger",
                            Line1 = "955 Flavie Freeway",
                            Line2 = "Suite 245",
                            Line3 = "Suite 797",
                            Name = "hack red",
                            PostalCode = "58342",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 79,
                            BookEntryId = 40,
                            CityTown = "Gleasonburgh",
                            Country = "Costa Rica",
                            Line1 = "39347 Reece Bridge",
                            Line3 = "Suite 389",
                            Name = "Plaza Plains",
                            PostalCode = "59529",
                            StateProvince = "Tennessee"
                        },
                        new
                        {
                            Id = 80,
                            BookEntryId = 40,
                            CityTown = "Vidafurt",
                            Country = "Greenland",
                            Line1 = "08311 Otto Meadows",
                            Line3 = "Apt. 563",
                            Name = "Personal Loan Account SCSI",
                            PostalCode = "34045",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 81,
                            BookEntryId = 41,
                            CityTown = "New Olaf",
                            Country = "Libyan Arab Jamahiriya",
                            Line1 = "09168 Jena Fall",
                            Line2 = "Suite 049",
                            Line3 = "Suite 952",
                            Name = "Rustic Views",
                            PostalCode = "58868",
                            StateProvince = "Kansas"
                        },
                        new
                        {
                            Id = 82,
                            BookEntryId = 41,
                            CityTown = "Port Hassie",
                            Country = "Guam",
                            Line1 = "7895 Cary Mountains",
                            Line2 = "Suite 391",
                            Line3 = "Suite 358",
                            Name = "Money Market Account Fresh",
                            PostalCode = "62148",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 83,
                            BookEntryId = 42,
                            CityTown = "Reingerchester",
                            Country = "Jamaica",
                            Line1 = "46625 Heller Roads",
                            Line2 = "Suite 579",
                            Line3 = "Apt. 978",
                            Name = "Soft scalable",
                            PostalCode = "36401-5460",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 84,
                            BookEntryId = 42,
                            CityTown = "Lake Hayleefort",
                            Country = "Marshall Islands",
                            Line1 = "504 Carey Flat",
                            Line3 = "Suite 717",
                            Name = "hard drive Devolved",
                            PostalCode = "19397-4086",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 85,
                            BookEntryId = 43,
                            CityTown = "East Declanland",
                            Country = "Somalia",
                            Line1 = "76715 Rhoda Locks",
                            Line2 = "Suite 872",
                            Line3 = "Apt. 706",
                            Name = "Accounts payment",
                            PostalCode = "55789-9519",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 86,
                            BookEntryId = 43,
                            CityTown = "Feeneyton",
                            Country = "Palestinian Territory",
                            Line1 = "9773 Sanford Well",
                            Line3 = "Suite 293",
                            Name = "engage synergize",
                            PostalCode = "50252",
                            StateProvince = "Wisconsin"
                        },
                        new
                        {
                            Id = 87,
                            BookEntryId = 44,
                            CityTown = "Jaskolskiport",
                            Country = "Sri Lanka",
                            Line1 = "7140 Percy Tunnel",
                            Line2 = "Apt. 856",
                            Line3 = "Suite 046",
                            Name = "Rustic Metal Bike Russian Ruble",
                            PostalCode = "62572-6183",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 88,
                            BookEntryId = 44,
                            CityTown = "East Mabelberg",
                            Country = "Algeria",
                            Line1 = "4179 Koss Forks",
                            Line3 = "Apt. 829",
                            Name = "generate orange",
                            PostalCode = "49918",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 89,
                            BookEntryId = 45,
                            CityTown = "East Darianville",
                            Country = "Libyan Arab Jamahiriya",
                            Line1 = "883 Emmerich Run",
                            Line3 = "Suite 457",
                            Name = "user-centric lime",
                            PostalCode = "85261",
                            StateProvince = "Mississippi"
                        },
                        new
                        {
                            Id = 90,
                            BookEntryId = 45,
                            CityTown = "Barrowsport",
                            Country = "Denmark",
                            Line1 = "323 Nikita Motorway",
                            Line2 = "Apt. 504",
                            Line3 = "Apt. 622",
                            Name = "Avon Berkshire",
                            PostalCode = "73152",
                            StateProvince = "Montana"
                        },
                        new
                        {
                            Id = 91,
                            BookEntryId = 46,
                            CityTown = "South Rhea",
                            Country = "Belize",
                            Line1 = "7689 Fay Bypass",
                            Line2 = "Suite 913",
                            Line3 = "Apt. 982",
                            Name = "Berkshire Practical",
                            PostalCode = "53370",
                            StateProvince = "Texas"
                        },
                        new
                        {
                            Id = 92,
                            BookEntryId = 46,
                            CityTown = "Lake Addieshire",
                            Country = "South Africa",
                            Line1 = "311 Adolfo Drives",
                            Line3 = "Apt. 533",
                            Name = "override Solutions",
                            PostalCode = "66398",
                            StateProvince = "New Jersey"
                        },
                        new
                        {
                            Id = 93,
                            BookEntryId = 47,
                            CityTown = "North Brownhaven",
                            Country = "Central African Republic",
                            Line1 = "322 Adalberto Crescent",
                            Line3 = "Suite 751",
                            Name = "Handmade Concrete Gloves navigate",
                            PostalCode = "92274-8376",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 94,
                            BookEntryId = 47,
                            CityTown = "New Alexane",
                            Country = "Denmark",
                            Line1 = "634 Halvorson Harbor",
                            Line2 = "Suite 115",
                            Line3 = "Apt. 362",
                            Name = "Mountain Small",
                            PostalCode = "48065",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 95,
                            BookEntryId = 48,
                            CityTown = "South Wilfordfort",
                            Country = "Malta",
                            Line1 = "5714 Estevan Stream",
                            Line3 = "Apt. 399",
                            Name = "Gorgeous turquoise",
                            PostalCode = "42072",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 96,
                            BookEntryId = 48,
                            CityTown = "New Lorenzton",
                            Country = "Romania",
                            Line1 = "74529 Garrett Landing",
                            Line3 = "Apt. 171",
                            Name = "Chief Cotton",
                            PostalCode = "63202",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 97,
                            BookEntryId = 49,
                            CityTown = "West Dylantown",
                            Country = "Gambia",
                            Line1 = "4574 Eleanora Burg",
                            Line3 = "Apt. 171",
                            Name = "Somoni withdrawal",
                            PostalCode = "03270",
                            StateProvince = "Colorado"
                        },
                        new
                        {
                            Id = 98,
                            BookEntryId = 49,
                            CityTown = "New Torrance",
                            Country = "Switzerland",
                            Line1 = "698 Collier Trace",
                            Line3 = "Suite 546",
                            Name = "Handcrafted Fresh Tuna Oregon",
                            PostalCode = "02031-3073",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 99,
                            BookEntryId = 50,
                            CityTown = "New Shaunfort",
                            Country = "Saint Barthelemy",
                            Line1 = "1216 Bosco Ferry",
                            Line3 = "Suite 398",
                            Name = "web services salmon",
                            PostalCode = "58087-6039",
                            StateProvince = "Indiana"
                        },
                        new
                        {
                            Id = 100,
                            BookEntryId = 50,
                            CityTown = "West Marcella",
                            Country = "Netherlands Antilles",
                            Line1 = "237 Nienow Landing",
                            Line2 = "Apt. 808",
                            Line3 = "Apt. 199",
                            Name = "Buckinghamshire Buckinghamshire",
                            PostalCode = "28913",
                            StateProvince = "Iowa"
                        });
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.BookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookEntries");

                    b.HasData(
                        new
                        {
                            Id = 26,
                            CellPhone = "830-799-4314",
                            CompanyName = "Daugherty - Yundt",
                            DateOfBirth = new DateTime(1957, 9, 1, 12, 37, 47, 500, DateTimeKind.Local).AddTicks(1217),
                            Email = "Nikko7@yahoo.com",
                            FirstName = "Nikko",
                            Gender = "Female",
                            HomePhone = "321-564-9581",
                            LastName = "Walsh",
                            MiddleName = "Fanny",
                            WorkPhone = "868-806-1235"
                        },
                        new
                        {
                            Id = 27,
                            CellPhone = "381-428-1380",
                            CompanyName = "Weissnat, Jacobs and Klein",
                            DateOfBirth = new DateTime(2003, 10, 12, 16, 21, 10, 471, DateTimeKind.Local).AddTicks(5759),
                            Email = "Jeanne48@hotmail.com",
                            FirstName = "Jeanne",
                            Gender = "Male",
                            HomePhone = "403-464-9914",
                            LastName = "O'Keefe",
                            MiddleName = "Randi"
                        },
                        new
                        {
                            Id = 28,
                            CompanyName = "Stroman - Hamill",
                            DateOfBirth = new DateTime(1987, 2, 12, 19, 0, 10, 778, DateTimeKind.Local).AddTicks(2899),
                            Email = "Shannon_DuBuque72@hotmail.com",
                            FirstName = "Shannon",
                            Gender = "Male",
                            HomePhone = "688-943-1740",
                            LastName = "DuBuque",
                            MiddleName = "Wilfred",
                            WorkPhone = "416-378-0335"
                        },
                        new
                        {
                            Id = 29,
                            CompanyName = "Yost Inc",
                            DateOfBirth = new DateTime(1999, 9, 16, 4, 26, 51, 675, DateTimeKind.Local).AddTicks(2747),
                            Email = "Skylar45@yahoo.com",
                            FirstName = "Skylar",
                            Gender = "Male",
                            LastName = "Hessel",
                            MiddleName = "Serenity",
                            WorkPhone = "766-525-8579"
                        },
                        new
                        {
                            Id = 30,
                            CompanyName = "Kirlin, Schamberger and Nicolas",
                            DateOfBirth = new DateTime(1955, 5, 29, 19, 23, 24, 732, DateTimeKind.Local).AddTicks(6598),
                            Email = "Moises_Lowe@gmail.com",
                            FirstName = "Moises",
                            Gender = "Female",
                            HomePhone = "317-365-5789",
                            LastName = "Lowe",
                            MiddleName = "Cheyenne",
                            WorkPhone = "698-335-3493"
                        },
                        new
                        {
                            Id = 31,
                            CompanyName = "Murphy Inc",
                            DateOfBirth = new DateTime(1987, 4, 29, 4, 6, 12, 611, DateTimeKind.Local).AddTicks(1569),
                            Email = "Samanta57@yahoo.com",
                            FirstName = "Samanta",
                            Gender = "Female",
                            HomePhone = "858-996-0082",
                            LastName = "Smith",
                            MiddleName = "Erik"
                        },
                        new
                        {
                            Id = 32,
                            CellPhone = "862-507-6899",
                            CompanyName = "Feeney and Sons",
                            DateOfBirth = new DateTime(1976, 5, 1, 18, 1, 36, 242, DateTimeKind.Local).AddTicks(4358),
                            Email = "Graham28@hotmail.com",
                            FirstName = "Graham",
                            Gender = "Male",
                            HomePhone = "370-498-2324",
                            LastName = "Konopelski",
                            MiddleName = "Ben",
                            WorkPhone = "853-537-0071"
                        },
                        new
                        {
                            Id = 33,
                            CompanyName = "Johnston, Schulist and Howell",
                            DateOfBirth = new DateTime(1996, 9, 20, 7, 29, 26, 455, DateTimeKind.Local).AddTicks(6507),
                            Email = "Mikel_Cruickshank@gmail.com",
                            FirstName = "Mikel",
                            Gender = "Male",
                            HomePhone = "511-755-0362",
                            LastName = "Cruickshank",
                            MiddleName = "Margarita"
                        },
                        new
                        {
                            Id = 34,
                            CompanyName = "Hettinger and Sons",
                            DateOfBirth = new DateTime(1961, 8, 27, 11, 36, 17, 352, DateTimeKind.Local).AddTicks(2376),
                            Email = "Mariane63@yahoo.com",
                            FirstName = "Mariane",
                            Gender = "Male",
                            LastName = "Fadel",
                            MiddleName = "Geovanny"
                        },
                        new
                        {
                            Id = 35,
                            CellPhone = "860-839-7464",
                            CompanyName = "Schinner, Goldner and Schimmel",
                            DateOfBirth = new DateTime(1976, 4, 28, 11, 22, 56, 161, DateTimeKind.Local).AddTicks(9473),
                            Email = "Kamryn.Boyle13@hotmail.com",
                            FirstName = "Kamryn",
                            Gender = "Male",
                            LastName = "Boyle",
                            MiddleName = "Russ"
                        },
                        new
                        {
                            Id = 36,
                            CompanyName = "Lind - Mosciski",
                            DateOfBirth = new DateTime(1996, 11, 10, 14, 4, 43, 206, DateTimeKind.Local).AddTicks(2316),
                            Email = "Edna63@gmail.com",
                            FirstName = "Edna",
                            Gender = "Male",
                            LastName = "Barrows",
                            MiddleName = "Ellis"
                        },
                        new
                        {
                            Id = 37,
                            CompanyName = "Wuckert - Bergnaum",
                            DateOfBirth = new DateTime(1971, 12, 25, 19, 15, 6, 468, DateTimeKind.Local).AddTicks(225),
                            Email = "Fannie_Luettgen@hotmail.com",
                            FirstName = "Fannie",
                            Gender = "Female",
                            HomePhone = "921-502-3443",
                            LastName = "Luettgen",
                            MiddleName = "Jessica",
                            WorkPhone = "937-242-8137"
                        },
                        new
                        {
                            Id = 38,
                            CompanyName = "Bergstrom - Price",
                            DateOfBirth = new DateTime(1978, 1, 3, 13, 58, 49, 765, DateTimeKind.Local).AddTicks(1870),
                            Email = "Leonor.Brown84@yahoo.com",
                            FirstName = "Leonor",
                            Gender = "Female",
                            HomePhone = "841-455-9375",
                            LastName = "Brown",
                            MiddleName = "Andres"
                        },
                        new
                        {
                            Id = 39,
                            CompanyName = "Bailey Inc",
                            DateOfBirth = new DateTime(1980, 3, 31, 10, 43, 13, 371, DateTimeKind.Local).AddTicks(8492),
                            Email = "Judge_Wisoky@hotmail.com",
                            FirstName = "Judge",
                            Gender = "Female",
                            HomePhone = "210-905-0189",
                            LastName = "Wisoky",
                            MiddleName = "Kali"
                        },
                        new
                        {
                            Id = 40,
                            CompanyName = "Gulgowski Group",
                            DateOfBirth = new DateTime(1988, 8, 6, 7, 41, 7, 875, DateTimeKind.Local).AddTicks(8980),
                            Email = "Cordelia_Halvorson92@yahoo.com",
                            FirstName = "Cordelia",
                            Gender = "Female",
                            LastName = "Halvorson",
                            MiddleName = "Elliott"
                        },
                        new
                        {
                            Id = 41,
                            CellPhone = "364-666-5317",
                            CompanyName = "Wisoky LLC",
                            DateOfBirth = new DateTime(1993, 3, 16, 10, 37, 17, 151, DateTimeKind.Local).AddTicks(1165),
                            Email = "Citlalli.Rogahn61@hotmail.com",
                            FirstName = "Citlalli",
                            Gender = "Male",
                            LastName = "Rogahn",
                            MiddleName = "May"
                        },
                        new
                        {
                            Id = 42,
                            CellPhone = "491-764-8356",
                            CompanyName = "Stokes, Bradtke and Mills",
                            DateOfBirth = new DateTime(1957, 12, 20, 12, 58, 28, 698, DateTimeKind.Local).AddTicks(6247),
                            Email = "Lea.Grant41@gmail.com",
                            FirstName = "Lea",
                            Gender = "Male",
                            HomePhone = "792-950-9751",
                            LastName = "Grant",
                            MiddleName = "Winifred"
                        },
                        new
                        {
                            Id = 43,
                            CompanyName = "Crooks - Leffler",
                            DateOfBirth = new DateTime(1991, 1, 13, 7, 10, 47, 420, DateTimeKind.Local).AddTicks(9125),
                            Email = "Vernon87@gmail.com",
                            FirstName = "Vernon",
                            Gender = "Male",
                            HomePhone = "995-660-2184",
                            LastName = "Runolfsson",
                            MiddleName = "Axel"
                        },
                        new
                        {
                            Id = 44,
                            CellPhone = "213-581-9061",
                            CompanyName = "Moen, Considine and Ortiz",
                            DateOfBirth = new DateTime(1955, 7, 25, 15, 45, 34, 578, DateTimeKind.Local).AddTicks(889),
                            Email = "Jess.Leffler@yahoo.com",
                            FirstName = "Jess",
                            Gender = "Male",
                            HomePhone = "266-460-0625",
                            LastName = "Leffler",
                            MiddleName = "Bennie"
                        },
                        new
                        {
                            Id = 45,
                            CompanyName = "Hauck - Will",
                            DateOfBirth = new DateTime(1975, 8, 28, 13, 4, 9, 322, DateTimeKind.Local).AddTicks(3950),
                            Email = "Arno.Kling23@gmail.com",
                            FirstName = "Arno",
                            Gender = "Male",
                            LastName = "Kling",
                            MiddleName = "Kaylie",
                            WorkPhone = "914-995-3197"
                        },
                        new
                        {
                            Id = 46,
                            CompanyName = "Weimann, Stroman and Koch",
                            DateOfBirth = new DateTime(1958, 8, 8, 20, 49, 46, 868, DateTimeKind.Local).AddTicks(9749),
                            Email = "Mitchel.Wuckert@hotmail.com",
                            FirstName = "Mitchel",
                            Gender = "Male",
                            HomePhone = "472-337-5097",
                            LastName = "Wuckert",
                            MiddleName = "Angelina"
                        },
                        new
                        {
                            Id = 47,
                            CompanyName = "Weber - Crist",
                            DateOfBirth = new DateTime(1982, 10, 10, 19, 3, 44, 884, DateTimeKind.Local).AddTicks(8441),
                            Email = "Raul_Effertz82@gmail.com",
                            FirstName = "Raul",
                            Gender = "Female",
                            LastName = "Effertz",
                            MiddleName = "Emilio",
                            WorkPhone = "587-353-3155"
                        },
                        new
                        {
                            Id = 48,
                            CellPhone = "666-270-9743",
                            CompanyName = "Kunze, Medhurst and Abshire",
                            DateOfBirth = new DateTime(1983, 7, 16, 5, 47, 6, 320, DateTimeKind.Local).AddTicks(5316),
                            Email = "Antwon.Kassulke@gmail.com",
                            FirstName = "Antwon",
                            Gender = "Male",
                            LastName = "Kassulke",
                            MiddleName = "Lowell"
                        },
                        new
                        {
                            Id = 49,
                            CellPhone = "565-482-0966",
                            CompanyName = "Stiedemann - Aufderhar",
                            DateOfBirth = new DateTime(1997, 5, 13, 19, 39, 22, 972, DateTimeKind.Local).AddTicks(5367),
                            Email = "Richmond28@gmail.com",
                            FirstName = "Richmond",
                            Gender = "Female",
                            HomePhone = "494-280-2551",
                            LastName = "Ferry",
                            MiddleName = "Shane"
                        },
                        new
                        {
                            Id = 50,
                            CompanyName = "Cruickshank LLC",
                            DateOfBirth = new DateTime(1997, 4, 5, 12, 2, 38, 427, DateTimeKind.Local).AddTicks(5967),
                            Email = "Camden91@yahoo.com",
                            FirstName = "Camden",
                            Gender = "Female",
                            HomePhone = "374-855-5304",
                            LastName = "Crona",
                            MiddleName = "Joana"
                        });
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.Address", b =>
                {
                    b.HasOne("AddressBook.Api.Data.Entities.BookEntry", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.BookEntry", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
