// <auto-generated />
using System;
using AddressBook.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressBook.Api.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20240117203030_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressBook.Api.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookEntryId")
                        .HasColumnType("int");

                    b.Property<string>("CityTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookEntryId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 50,
                            BookEntryId = 103,
                            CityTown = "Dachbury",
                            Country = "Belize",
                            Line1 = "790 Luigi Port",
                            Line3 = "Suite 386",
                            Name = "Extended synergies",
                            PostalCode = "93144",
                            StateProvince = "Michigan"
                        },
                        new
                        {
                            Id = 51,
                            BookEntryId = 109,
                            CityTown = "South Daniela",
                            Country = "Qatar",
                            Line1 = "906 Corene Lodge",
                            Line2 = "Suite 210",
                            Line3 = "Suite 163",
                            Name = "Auto Loan Account modular",
                            PostalCode = "51243-5980",
                            StateProvince = "New York"
                        },
                        new
                        {
                            Id = 52,
                            BookEntryId = 110,
                            CityTown = "Alyceberg",
                            Country = "Reunion",
                            Line1 = "61298 Purdy Mountains",
                            Line2 = "Suite 387",
                            Line3 = "Apt. 740",
                            Name = "Credit Card Account yellow",
                            PostalCode = "07402-9994",
                            StateProvince = "Missouri"
                        },
                        new
                        {
                            Id = 53,
                            BookEntryId = 111,
                            CityTown = "Kiehnside",
                            Country = "Virgin Islands, U.S.",
                            Line1 = "9972 Dayna Knoll",
                            Line2 = "Apt. 592",
                            Line3 = "Apt. 469",
                            Name = "Customer synthesize",
                            PostalCode = "69633",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 54,
                            BookEntryId = 113,
                            CityTown = "Fritschtown",
                            Country = "Falkland Islands (Malvinas)",
                            Line1 = "5734 Quinton Stravenue",
                            Line3 = "Suite 019",
                            Name = "Personal Loan Account Developer",
                            PostalCode = "64354",
                            StateProvince = "Pennsylvania"
                        },
                        new
                        {
                            Id = 55,
                            BookEntryId = 114,
                            CityTown = "South Augustusside",
                            Country = "Haiti",
                            Line1 = "8104 Pinkie Divide",
                            Line3 = "Suite 286",
                            Name = "alarm Designer",
                            PostalCode = "31291",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 56,
                            BookEntryId = 115,
                            CityTown = "South Reyna",
                            Country = "Albania",
                            Line1 = "515 Meaghan Drive",
                            Line3 = "Apt. 098",
                            Name = "PCI Generic Granite Chair",
                            PostalCode = "79122-7917",
                            StateProvince = "New Jersey"
                        },
                        new
                        {
                            Id = 57,
                            BookEntryId = 116,
                            CityTown = "Noetown",
                            Country = "Isle of Man",
                            Line1 = "91117 Satterfield Rapids",
                            Line3 = "Apt. 027",
                            Name = "sky blue District",
                            PostalCode = "73120-0914",
                            StateProvince = "Indiana"
                        },
                        new
                        {
                            Id = 58,
                            BookEntryId = 117,
                            CityTown = "Port Theodora",
                            Country = "Jamaica",
                            Line1 = "598 Schuppe Knolls",
                            Line2 = "Apt. 059",
                            Line3 = "Suite 986",
                            Name = "reboot Belize Dollar",
                            PostalCode = "80782",
                            StateProvince = "New Hampshire"
                        },
                        new
                        {
                            Id = 59,
                            BookEntryId = 120,
                            CityTown = "Emmerichland",
                            Country = "Tunisia",
                            Line1 = "67998 Willy Views",
                            Line3 = "Apt. 675",
                            Name = "Incredible pink",
                            PostalCode = "76663-3736",
                            StateProvince = "New York"
                        },
                        new
                        {
                            Id = 60,
                            BookEntryId = 122,
                            CityTown = "East Uriah",
                            Country = "Botswana",
                            Line1 = "9297 Wunsch Road",
                            Line2 = "Suite 073",
                            Line3 = "Suite 589",
                            Name = "synthesize USB",
                            PostalCode = "54324",
                            StateProvince = "Connecticut"
                        },
                        new
                        {
                            Id = 61,
                            BookEntryId = 123,
                            CityTown = "Maymiebury",
                            Country = "Isle of Man",
                            Line1 = "64798 Feil Knoll",
                            Line2 = "Suite 509",
                            Line3 = "Apt. 080",
                            Name = "web-enabled back up",
                            PostalCode = "26956",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 62,
                            BookEntryId = 125,
                            CityTown = "South Carmelmouth",
                            Country = "Algeria",
                            Line1 = "839 Leffler Walk",
                            Line3 = "Apt. 305",
                            Name = "Burgs upward-trending",
                            PostalCode = "10523-4057",
                            StateProvince = "Florida"
                        },
                        new
                        {
                            Id = 63,
                            BookEntryId = 129,
                            CityTown = "Raphaelborough",
                            Country = "New Zealand",
                            Line1 = "048 Meagan Creek",
                            Line2 = "Apt. 415",
                            Line3 = "Apt. 877",
                            Name = "Isle Groves",
                            PostalCode = "16864",
                            StateProvince = "Virginia"
                        },
                        new
                        {
                            Id = 64,
                            BookEntryId = 131,
                            CityTown = "Muellershire",
                            Country = "Central African Republic",
                            Line1 = "6133 Evie Locks",
                            Line2 = "Suite 018",
                            Line3 = "Suite 692",
                            Name = "synergies Orchestrator",
                            PostalCode = "00340",
                            StateProvince = "Delaware"
                        },
                        new
                        {
                            Id = 65,
                            BookEntryId = 132,
                            CityTown = "East Sophiaborough",
                            Country = "United States of America",
                            Line1 = "4902 Zachariah Lane",
                            Line2 = "Apt. 827",
                            Name = "indexing Unbranded Metal Bacon",
                            PostalCode = "62205",
                            StateProvince = "Maryland"
                        },
                        new
                        {
                            Id = 66,
                            BookEntryId = 133,
                            CityTown = "Port Mariannachester",
                            Country = "Iran",
                            Line1 = "2920 Zetta Centers",
                            Line3 = "Suite 946",
                            Name = "SAS Intelligent Granite Sausages",
                            PostalCode = "06094-6412",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 67,
                            BookEntryId = 136,
                            CityTown = "Mayertside",
                            Country = "Ukraine",
                            Line1 = "97339 Dena Avenue",
                            Line3 = "Apt. 169",
                            Name = "program Customer-focused",
                            PostalCode = "08348-2024",
                            StateProvince = "Illinois"
                        },
                        new
                        {
                            Id = 68,
                            BookEntryId = 137,
                            CityTown = "Boyleburgh",
                            Country = "Nepal",
                            Line1 = "91287 Hessel Creek",
                            Line2 = "Apt. 218",
                            Line3 = "Apt. 049",
                            Name = "1080p mindshare",
                            PostalCode = "78097",
                            StateProvince = "Virginia"
                        },
                        new
                        {
                            Id = 69,
                            BookEntryId = 139,
                            CityTown = "Lake Rhiannonhaven",
                            Country = "Micronesia",
                            Line1 = "58961 Pearlie Forge",
                            Line3 = "Suite 377",
                            Name = "next generation Quality",
                            PostalCode = "02109",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 70,
                            BookEntryId = 140,
                            CityTown = "East Jeffrey",
                            Country = "Benin",
                            Line1 = "79678 Bernadine Plain",
                            Line2 = "Suite 824",
                            Line3 = "Apt. 544",
                            Name = "Intelligent Soft Salad generating",
                            PostalCode = "62999-4407",
                            StateProvince = "New Hampshire"
                        },
                        new
                        {
                            Id = 71,
                            BookEntryId = 141,
                            CityTown = "Port Maritza",
                            Country = "Niger",
                            Line1 = "8469 Kaylah Glens",
                            Line3 = "Suite 662",
                            Name = "payment Rustic Wooden Chips",
                            PostalCode = "28432",
                            StateProvince = "Rhode Island"
                        },
                        new
                        {
                            Id = 72,
                            BookEntryId = 143,
                            CityTown = "New Amariton",
                            Country = "Cayman Islands",
                            Line1 = "773 Aimee Overpass",
                            Line2 = "Suite 309",
                            Line3 = "Suite 509",
                            Name = "French Guiana forecast",
                            PostalCode = "34304-3101",
                            StateProvince = "New Jersey"
                        },
                        new
                        {
                            Id = 73,
                            BookEntryId = 146,
                            CityTown = "Ashleebury",
                            Country = "Benin",
                            Line1 = "43339 Mills Route",
                            Line3 = "Suite 351",
                            Name = "Auto Loan Account distributed",
                            PostalCode = "61973-9763",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 74,
                            BookEntryId = 148,
                            CityTown = "Bayleeburgh",
                            Country = "British Indian Ocean Territory (Chagos Archipelago)",
                            Line1 = "2164 Crooks Lodge",
                            Line2 = "Suite 581",
                            Line3 = "Suite 868",
                            Name = "Chief Isle",
                            PostalCode = "99053-6278",
                            StateProvince = "Louisiana"
                        },
                        new
                        {
                            Id = 75,
                            BookEntryId = 150,
                            CityTown = "East Jakob",
                            Country = "Palestinian Territory",
                            Line1 = "248 Rohan Circle",
                            Line3 = "Suite 728",
                            Name = "Shoes Chief",
                            PostalCode = "28670-9571",
                            StateProvince = "Florida"
                        },
                        new
                        {
                            Id = 76,
                            BookEntryId = 151,
                            CityTown = "Trudiebury",
                            Country = "Burundi",
                            Line1 = "86811 Jared Expressway",
                            Line2 = "Suite 081",
                            Line3 = "Apt. 742",
                            Name = "Dynamic Security",
                            PostalCode = "86138",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 77,
                            BookEntryId = 152,
                            CityTown = "Yostbury",
                            Country = "Palestinian Territory",
                            Line1 = "64991 Alexa Isle",
                            Line3 = "Apt. 835",
                            Name = "gold Fantastic Fresh Computer",
                            PostalCode = "53062",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 78,
                            BookEntryId = 153,
                            CityTown = "Faheymouth",
                            Country = "Niger",
                            Line1 = "955 Flavie Freeway",
                            Line2 = "Suite 245",
                            Line3 = "Suite 797",
                            Name = "hack red",
                            PostalCode = "58342",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 79,
                            BookEntryId = 154,
                            CityTown = "Gleasonburgh",
                            Country = "Costa Rica",
                            Line1 = "39347 Reece Bridge",
                            Line3 = "Suite 389",
                            Name = "Plaza Plains",
                            PostalCode = "59529",
                            StateProvince = "Tennessee"
                        },
                        new
                        {
                            Id = 80,
                            BookEntryId = 156,
                            CityTown = "Vidafurt",
                            Country = "Greenland",
                            Line1 = "08311 Otto Meadows",
                            Line3 = "Apt. 563",
                            Name = "Personal Loan Account SCSI",
                            PostalCode = "34045",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 81,
                            BookEntryId = 158,
                            CityTown = "New Olaf",
                            Country = "Libyan Arab Jamahiriya",
                            Line1 = "09168 Jena Fall",
                            Line2 = "Suite 049",
                            Line3 = "Suite 952",
                            Name = "Rustic Views",
                            PostalCode = "58868",
                            StateProvince = "Kansas"
                        },
                        new
                        {
                            Id = 82,
                            BookEntryId = 160,
                            CityTown = "Port Hassie",
                            Country = "Guam",
                            Line1 = "7895 Cary Mountains",
                            Line2 = "Suite 391",
                            Line3 = "Suite 358",
                            Name = "Money Market Account Fresh",
                            PostalCode = "62148",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 83,
                            BookEntryId = 161,
                            CityTown = "Reingerchester",
                            Country = "Jamaica",
                            Line1 = "46625 Heller Roads",
                            Line2 = "Suite 579",
                            Line3 = "Apt. 978",
                            Name = "Soft scalable",
                            PostalCode = "36401-5460",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 84,
                            BookEntryId = 163,
                            CityTown = "Lake Hayleefort",
                            Country = "Marshall Islands",
                            Line1 = "504 Carey Flat",
                            Line3 = "Suite 717",
                            Name = "hard drive Devolved",
                            PostalCode = "19397-4086",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 85,
                            BookEntryId = 170,
                            CityTown = "East Declanland",
                            Country = "Somalia",
                            Line1 = "76715 Rhoda Locks",
                            Line2 = "Suite 872",
                            Line3 = "Apt. 706",
                            Name = "Accounts payment",
                            PostalCode = "55789-9519",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 86,
                            BookEntryId = 172,
                            CityTown = "Feeneyton",
                            Country = "Palestinian Territory",
                            Line1 = "9773 Sanford Well",
                            Line3 = "Suite 293",
                            Name = "engage synergize",
                            PostalCode = "50252",
                            StateProvince = "Wisconsin"
                        },
                        new
                        {
                            Id = 87,
                            BookEntryId = 174,
                            CityTown = "Jaskolskiport",
                            Country = "Sri Lanka",
                            Line1 = "7140 Percy Tunnel",
                            Line2 = "Apt. 856",
                            Line3 = "Suite 046",
                            Name = "Rustic Metal Bike Russian Ruble",
                            PostalCode = "62572-6183",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 88,
                            BookEntryId = 175,
                            CityTown = "East Mabelberg",
                            Country = "Algeria",
                            Line1 = "4179 Koss Forks",
                            Line3 = "Apt. 829",
                            Name = "generate orange",
                            PostalCode = "49918",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 89,
                            BookEntryId = 177,
                            CityTown = "East Darianville",
                            Country = "Libyan Arab Jamahiriya",
                            Line1 = "883 Emmerich Run",
                            Line3 = "Suite 457",
                            Name = "user-centric lime",
                            PostalCode = "85261",
                            StateProvince = "Mississippi"
                        },
                        new
                        {
                            Id = 90,
                            BookEntryId = 178,
                            CityTown = "Barrowsport",
                            Country = "Denmark",
                            Line1 = "323 Nikita Motorway",
                            Line2 = "Apt. 504",
                            Line3 = "Apt. 622",
                            Name = "Avon Berkshire",
                            PostalCode = "73152",
                            StateProvince = "Montana"
                        },
                        new
                        {
                            Id = 91,
                            BookEntryId = 181,
                            CityTown = "South Rhea",
                            Country = "Belize",
                            Line1 = "7689 Fay Bypass",
                            Line2 = "Suite 913",
                            Line3 = "Apt. 982",
                            Name = "Berkshire Practical",
                            PostalCode = "53370",
                            StateProvince = "Texas"
                        },
                        new
                        {
                            Id = 92,
                            BookEntryId = 182,
                            CityTown = "Lake Addieshire",
                            Country = "South Africa",
                            Line1 = "311 Adolfo Drives",
                            Line3 = "Apt. 533",
                            Name = "override Solutions",
                            PostalCode = "66398",
                            StateProvince = "New Jersey"
                        },
                        new
                        {
                            Id = 93,
                            BookEntryId = 183,
                            CityTown = "North Brownhaven",
                            Country = "Central African Republic",
                            Line1 = "322 Adalberto Crescent",
                            Line3 = "Suite 751",
                            Name = "Handmade Concrete Gloves navigate",
                            PostalCode = "92274-8376",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 94,
                            BookEntryId = 186,
                            CityTown = "New Alexane",
                            Country = "Denmark",
                            Line1 = "634 Halvorson Harbor",
                            Line2 = "Suite 115",
                            Line3 = "Apt. 362",
                            Name = "Mountain Small",
                            PostalCode = "48065",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 95,
                            BookEntryId = 187,
                            CityTown = "South Wilfordfort",
                            Country = "Malta",
                            Line1 = "5714 Estevan Stream",
                            Line3 = "Apt. 399",
                            Name = "Gorgeous turquoise",
                            PostalCode = "42072",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 96,
                            BookEntryId = 191,
                            CityTown = "New Lorenzton",
                            Country = "Romania",
                            Line1 = "74529 Garrett Landing",
                            Line3 = "Apt. 171",
                            Name = "Chief Cotton",
                            PostalCode = "63202",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 97,
                            BookEntryId = 193,
                            CityTown = "West Dylantown",
                            Country = "Gambia",
                            Line1 = "4574 Eleanora Burg",
                            Line3 = "Apt. 171",
                            Name = "Somoni withdrawal",
                            PostalCode = "03270",
                            StateProvince = "Colorado"
                        },
                        new
                        {
                            Id = 98,
                            BookEntryId = 194,
                            CityTown = "New Torrance",
                            Country = "Switzerland",
                            Line1 = "698 Collier Trace",
                            Line3 = "Suite 546",
                            Name = "Handcrafted Fresh Tuna Oregon",
                            PostalCode = "02031-3073",
                            StateProvince = "Hawaii"
                        },
                        new
                        {
                            Id = 99,
                            BookEntryId = 196,
                            CityTown = "New Shaunfort",
                            Country = "Saint Barthelemy",
                            Line1 = "1216 Bosco Ferry",
                            Line3 = "Suite 398",
                            Name = "web services salmon",
                            PostalCode = "58087-6039",
                            StateProvince = "Indiana"
                        },
                        new
                        {
                            Id = 100,
                            BookEntryId = 199,
                            CityTown = "West Marcella",
                            Country = "Netherlands Antilles",
                            Line1 = "237 Nienow Landing",
                            Line2 = "Apt. 808",
                            Line3 = "Apt. 199",
                            Name = "Buckinghamshire Buckinghamshire",
                            PostalCode = "28913",
                            StateProvince = "Iowa"
                        },
                        new
                        {
                            Id = 101,
                            BookEntryId = 200,
                            CityTown = "East Amiya",
                            Country = "Hungary",
                            Line1 = "3047 Mabelle Forge",
                            Line3 = "Suite 207",
                            Name = "executive Investment Account",
                            PostalCode = "77410-1754",
                            StateProvince = "South Carolina"
                        });
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.BookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookEntries");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CompanyName = "Ullrich, Rowe and Waters",
                            DateOfBirth = new DateTime(1994, 3, 25, 19, 42, 3, 197, DateTimeKind.Local).AddTicks(4600),
                            Email = "Deion_Goodwin@gmail.com",
                            FirstName = "Deion",
                            LastName = "Goodwin",
                            MiddleName = "Clemmie"
                        },
                        new
                        {
                            Id = 102,
                            CellPhone = "908-755-2931",
                            CompanyName = "Lebsack, Pfannerstill and Dicki",
                            DateOfBirth = new DateTime(1978, 6, 8, 6, 46, 52, 673, DateTimeKind.Local).AddTicks(2127),
                            Email = "Minerva_Rowe@hotmail.com",
                            FirstName = "Minerva",
                            LastName = "Rowe",
                            MiddleName = "Erwin",
                            WorkPhone = "887-902-4954"
                        },
                        new
                        {
                            Id = 103,
                            CompanyName = "Skiles, Wehner and Quigley",
                            DateOfBirth = new DateTime(2002, 7, 27, 11, 1, 39, 888, DateTimeKind.Local).AddTicks(2509),
                            Email = "Marty_Ritchie18@hotmail.com",
                            FirstName = "Marty",
                            LastName = "Ritchie",
                            MiddleName = "Gracie",
                            WorkPhone = "941-263-3754"
                        },
                        new
                        {
                            Id = 104,
                            CellPhone = "709-581-1775",
                            CompanyName = "Hegmann Group",
                            DateOfBirth = new DateTime(1980, 2, 18, 15, 47, 24, 325, DateTimeKind.Local).AddTicks(2339),
                            Email = "Erin.Ziemann@hotmail.com",
                            FirstName = "Erin",
                            Gender = "Male",
                            LastName = "Ziemann",
                            MiddleName = "Janet",
                            WorkPhone = "336-604-8959"
                        },
                        new
                        {
                            Id = 105,
                            CellPhone = "713-832-4613",
                            CompanyName = "Connelly, Skiles and Hyatt",
                            DateOfBirth = new DateTime(2000, 10, 17, 5, 50, 18, 430, DateTimeKind.Local).AddTicks(8822),
                            Email = "Jerry93@hotmail.com",
                            FirstName = "Jerry",
                            LastName = "Howell",
                            MiddleName = "Ellen",
                            WorkPhone = "896-702-7135"
                        },
                        new
                        {
                            Id = 106,
                            CompanyName = "Lockman, Padberg and O'Kon",
                            DateOfBirth = new DateTime(1956, 9, 26, 15, 30, 45, 437, DateTimeKind.Local).AddTicks(2962),
                            Email = "Rocky_Ankunding@gmail.com",
                            FirstName = "Rocky",
                            Gender = "Female",
                            HomePhone = "840-611-7073",
                            LastName = "Ankunding",
                            MiddleName = "Sheldon",
                            WorkPhone = "515-461-0390"
                        },
                        new
                        {
                            Id = 107,
                            CompanyName = "Parisian, Rohan and Friesen",
                            DateOfBirth = new DateTime(1987, 5, 29, 5, 7, 20, 415, DateTimeKind.Local).AddTicks(6752),
                            Email = "Charlotte_Sawayn@yahoo.com",
                            FirstName = "Charlotte",
                            LastName = "Sawayn",
                            MiddleName = "Rocky",
                            WorkPhone = "585-676-6280"
                        },
                        new
                        {
                            Id = 108,
                            CellPhone = "904-401-4522",
                            CompanyName = "Weimann and Sons",
                            DateOfBirth = new DateTime(1969, 1, 14, 22, 48, 24, 122, DateTimeKind.Local).AddTicks(6960),
                            Email = "Stanford.Murray12@gmail.com",
                            FirstName = "Stanford",
                            HomePhone = "713-847-5422",
                            LastName = "Murray",
                            MiddleName = "Donny"
                        },
                        new
                        {
                            Id = 109,
                            CompanyName = "Brekke Group",
                            DateOfBirth = new DateTime(2001, 4, 18, 5, 55, 31, 564, DateTimeKind.Local).AddTicks(5673),
                            Email = "Kiera_Ortiz@hotmail.com",
                            FirstName = "Kiera",
                            HomePhone = "801-876-1113",
                            LastName = "Ortiz",
                            MiddleName = "Elmore"
                        },
                        new
                        {
                            Id = 110,
                            CellPhone = "927-748-5153",
                            CompanyName = "Torp - Larson",
                            DateOfBirth = new DateTime(1958, 7, 3, 20, 32, 56, 610, DateTimeKind.Local).AddTicks(5096),
                            Email = "Freeda.Schmeler@gmail.com",
                            FirstName = "Freeda",
                            Gender = "Male",
                            HomePhone = "239-856-6524",
                            LastName = "Schmeler",
                            MiddleName = "Hoyt",
                            WorkPhone = "333-411-5856"
                        },
                        new
                        {
                            Id = 111,
                            CompanyName = "Muller Inc",
                            DateOfBirth = new DateTime(1995, 8, 20, 8, 10, 36, 322, DateTimeKind.Local).AddTicks(4203),
                            Email = "Angelica.Turner@gmail.com",
                            FirstName = "Angelica",
                            LastName = "Turner",
                            MiddleName = "Macey",
                            WorkPhone = "236-469-7755"
                        },
                        new
                        {
                            Id = 112,
                            CellPhone = "908-943-1439",
                            CompanyName = "Fisher LLC",
                            DateOfBirth = new DateTime(1974, 10, 21, 15, 30, 35, 489, DateTimeKind.Local).AddTicks(4482),
                            Email = "Rey81@gmail.com",
                            FirstName = "Rey",
                            Gender = "Male",
                            LastName = "Rowe",
                            MiddleName = "Cyrus",
                            WorkPhone = "960-552-6814"
                        },
                        new
                        {
                            Id = 113,
                            CellPhone = "266-660-2918",
                            CompanyName = "Gerhold, Willms and Daniel",
                            DateOfBirth = new DateTime(1998, 4, 18, 5, 47, 37, 559, DateTimeKind.Local).AddTicks(3901),
                            Email = "Emmanuelle76@hotmail.com",
                            FirstName = "Emmanuelle",
                            HomePhone = "304-839-1601",
                            LastName = "Gislason",
                            MiddleName = "Davon"
                        },
                        new
                        {
                            Id = 114,
                            CompanyName = "Bailey and Sons",
                            DateOfBirth = new DateTime(1962, 2, 12, 4, 39, 2, 533, DateTimeKind.Local).AddTicks(9146),
                            Email = "Zaria99@gmail.com",
                            FirstName = "Zaria",
                            Gender = "Male",
                            HomePhone = "536-563-0228",
                            LastName = "Rutherford",
                            MiddleName = "Ronaldo",
                            WorkPhone = "324-892-2128"
                        },
                        new
                        {
                            Id = 115,
                            CellPhone = "487-505-7203",
                            CompanyName = "Lesch Group",
                            DateOfBirth = new DateTime(1977, 12, 16, 21, 5, 46, 191, DateTimeKind.Local).AddTicks(4655),
                            Email = "King_Pagac@yahoo.com",
                            FirstName = "King",
                            LastName = "Pagac",
                            MiddleName = "Adolf"
                        },
                        new
                        {
                            Id = 116,
                            CompanyName = "Koch - Klein",
                            DateOfBirth = new DateTime(2003, 3, 17, 11, 11, 52, 230, DateTimeKind.Local).AddTicks(361),
                            Email = "Oswald_Olson38@yahoo.com",
                            FirstName = "Oswald",
                            Gender = "Female",
                            LastName = "Olson",
                            MiddleName = "Mathias",
                            WorkPhone = "556-938-1157"
                        },
                        new
                        {
                            Id = 117,
                            CellPhone = "708-298-4936",
                            CompanyName = "Kshlerin - Kutch",
                            DateOfBirth = new DateTime(1958, 4, 16, 5, 23, 9, 434, DateTimeKind.Local).AddTicks(2053),
                            Email = "Esta_Torphy3@yahoo.com",
                            FirstName = "Esta",
                            LastName = "Torphy",
                            MiddleName = "Raul",
                            WorkPhone = "515-225-2069"
                        },
                        new
                        {
                            Id = 118,
                            CellPhone = "445-376-9536",
                            CompanyName = "Stokes - Volkman",
                            DateOfBirth = new DateTime(1958, 3, 18, 18, 44, 33, 924, DateTimeKind.Local).AddTicks(1059),
                            Email = "Sebastian.Bartell2@gmail.com",
                            FirstName = "Sebastian",
                            Gender = "Female",
                            LastName = "Bartell",
                            MiddleName = "Eileen"
                        },
                        new
                        {
                            Id = 119,
                            CompanyName = "Keeling - Quigley",
                            DateOfBirth = new DateTime(1977, 10, 1, 10, 37, 12, 974, DateTimeKind.Local).AddTicks(2155),
                            Email = "Julio_Leffler@gmail.com",
                            FirstName = "Julio",
                            Gender = "Female",
                            LastName = "Leffler",
                            MiddleName = "Gustave",
                            WorkPhone = "536-796-7294"
                        },
                        new
                        {
                            Id = 120,
                            CellPhone = "545-381-1242",
                            CompanyName = "Metz, Wyman and Leannon",
                            DateOfBirth = new DateTime(2001, 7, 23, 18, 11, 28, 939, DateTimeKind.Local).AddTicks(2572),
                            Email = "Rosetta_Graham7@hotmail.com",
                            FirstName = "Rosetta",
                            Gender = "Male",
                            LastName = "Graham",
                            MiddleName = "Haskell",
                            WorkPhone = "428-232-2622"
                        },
                        new
                        {
                            Id = 121,
                            CompanyName = "Pfannerstill LLC",
                            DateOfBirth = new DateTime(1971, 4, 5, 12, 51, 4, 744, DateTimeKind.Local).AddTicks(9213),
                            Email = "Orie.Veum@gmail.com",
                            FirstName = "Orie",
                            Gender = "Female",
                            HomePhone = "570-687-2924",
                            LastName = "Veum",
                            MiddleName = "Nico",
                            WorkPhone = "354-894-8321"
                        },
                        new
                        {
                            Id = 122,
                            CompanyName = "Johnston, Hand and Gibson",
                            DateOfBirth = new DateTime(1991, 7, 10, 18, 11, 34, 383, DateTimeKind.Local).AddTicks(2236),
                            Email = "Enid90@hotmail.com",
                            FirstName = "Enid",
                            Gender = "Female",
                            LastName = "Stokes",
                            MiddleName = "Colleen"
                        },
                        new
                        {
                            Id = 123,
                            CompanyName = "Larson LLC",
                            DateOfBirth = new DateTime(1991, 11, 2, 3, 7, 4, 635, DateTimeKind.Local).AddTicks(4810),
                            Email = "Jakayla.Yundt@hotmail.com",
                            FirstName = "Jakayla",
                            Gender = "Male",
                            HomePhone = "440-333-3046",
                            LastName = "Yundt",
                            MiddleName = "Katelin",
                            WorkPhone = "698-917-8957"
                        },
                        new
                        {
                            Id = 124,
                            CompanyName = "Lubowitz - Rolfson",
                            DateOfBirth = new DateTime(1976, 2, 12, 14, 17, 25, 895, DateTimeKind.Local).AddTicks(9561),
                            Email = "Athena_King70@gmail.com",
                            FirstName = "Athena",
                            LastName = "King",
                            MiddleName = "Travon"
                        },
                        new
                        {
                            Id = 125,
                            CompanyName = "McLaughlin LLC",
                            DateOfBirth = new DateTime(1967, 10, 18, 15, 4, 45, 481, DateTimeKind.Local).AddTicks(2960),
                            Email = "Rodrigo_Kassulke@hotmail.com",
                            FirstName = "Rodrigo",
                            LastName = "Kassulke",
                            MiddleName = "Lina",
                            WorkPhone = "326-877-1572"
                        },
                        new
                        {
                            Id = 126,
                            CellPhone = "873-599-0475",
                            CompanyName = "Dach, Harvey and Kirlin",
                            DateOfBirth = new DateTime(1974, 2, 28, 4, 40, 48, 565, DateTimeKind.Local).AddTicks(9530),
                            Email = "Marcus_Goodwin@yahoo.com",
                            FirstName = "Marcus",
                            Gender = "Male",
                            HomePhone = "781-807-6411",
                            LastName = "Goodwin",
                            MiddleName = "Domenic",
                            WorkPhone = "490-687-5505"
                        },
                        new
                        {
                            Id = 127,
                            CompanyName = "Morissette, Wunsch and Hartmann",
                            DateOfBirth = new DateTime(1981, 8, 21, 17, 36, 10, 659, DateTimeKind.Local).AddTicks(6867),
                            Email = "Paul_Olson@yahoo.com",
                            FirstName = "Paul",
                            HomePhone = "988-294-2230",
                            LastName = "Olson",
                            MiddleName = "Eldora"
                        },
                        new
                        {
                            Id = 128,
                            CellPhone = "925-408-2706",
                            CompanyName = "Runte LLC",
                            DateOfBirth = new DateTime(1986, 4, 6, 20, 4, 43, 33, DateTimeKind.Local).AddTicks(9794),
                            Email = "Frances19@hotmail.com",
                            FirstName = "Frances",
                            Gender = "Male",
                            HomePhone = "400-827-7535",
                            LastName = "Von",
                            MiddleName = "Alexis",
                            WorkPhone = "663-952-2445"
                        },
                        new
                        {
                            Id = 129,
                            CompanyName = "Brakus and Sons",
                            DateOfBirth = new DateTime(2002, 2, 2, 13, 45, 53, 228, DateTimeKind.Local).AddTicks(7195),
                            Email = "Nikolas61@yahoo.com",
                            FirstName = "Nikolas",
                            HomePhone = "339-677-5182",
                            LastName = "Frami",
                            MiddleName = "Myrl",
                            WorkPhone = "599-624-3116"
                        },
                        new
                        {
                            Id = 130,
                            CompanyName = "Nolan - Toy",
                            DateOfBirth = new DateTime(1966, 2, 20, 12, 16, 20, 129, DateTimeKind.Local).AddTicks(39),
                            Email = "Katelin9@yahoo.com",
                            FirstName = "Katelin",
                            Gender = "Female",
                            HomePhone = "629-959-8722",
                            LastName = "Wisozk",
                            MiddleName = "Don",
                            WorkPhone = "527-328-0097"
                        },
                        new
                        {
                            Id = 131,
                            CompanyName = "Flatley and Sons",
                            DateOfBirth = new DateTime(1961, 4, 12, 9, 16, 53, 514, DateTimeKind.Local).AddTicks(8621),
                            Email = "Reuben_Moore19@yahoo.com",
                            FirstName = "Reuben",
                            Gender = "Male",
                            LastName = "Moore",
                            MiddleName = "Catalina"
                        },
                        new
                        {
                            Id = 132,
                            CompanyName = "Mertz Group",
                            DateOfBirth = new DateTime(1989, 12, 9, 14, 59, 25, 539, DateTimeKind.Local).AddTicks(3501),
                            Email = "Mikayla_Keeling82@yahoo.com",
                            FirstName = "Mikayla",
                            Gender = "Female",
                            LastName = "Keeling",
                            MiddleName = "Abbie",
                            WorkPhone = "407-812-7951"
                        },
                        new
                        {
                            Id = 133,
                            CellPhone = "422-468-8115",
                            CompanyName = "Casper, Bode and Hettinger",
                            DateOfBirth = new DateTime(1975, 2, 18, 4, 45, 51, 673, DateTimeKind.Local).AddTicks(1578),
                            Email = "Torrance_Hamill25@hotmail.com",
                            FirstName = "Torrance",
                            LastName = "Hamill",
                            MiddleName = "Juwan"
                        },
                        new
                        {
                            Id = 134,
                            CompanyName = "Konopelski - Satterfield",
                            DateOfBirth = new DateTime(1954, 9, 25, 22, 51, 11, 201, DateTimeKind.Local).AddTicks(7782),
                            Email = "Jayme.Jaskolski60@hotmail.com",
                            FirstName = "Jayme",
                            Gender = "Male",
                            LastName = "Jaskolski",
                            MiddleName = "Eva",
                            WorkPhone = "510-770-2969"
                        },
                        new
                        {
                            Id = 135,
                            CompanyName = "Cartwright and Sons",
                            DateOfBirth = new DateTime(1962, 4, 8, 19, 32, 23, 953, DateTimeKind.Local).AddTicks(9381),
                            Email = "Aleen73@hotmail.com",
                            FirstName = "Aleen",
                            HomePhone = "982-693-1909",
                            LastName = "Block",
                            MiddleName = "Jamar"
                        },
                        new
                        {
                            Id = 136,
                            CellPhone = "824-709-3197",
                            CompanyName = "Ziemann, Rohan and Mills",
                            DateOfBirth = new DateTime(1968, 11, 24, 0, 11, 26, 232, DateTimeKind.Local).AddTicks(4286),
                            Email = "Christiana.Feil@gmail.com",
                            FirstName = "Christiana",
                            Gender = "Female",
                            LastName = "Feil",
                            MiddleName = "Germaine"
                        },
                        new
                        {
                            Id = 137,
                            CompanyName = "Hyatt - DuBuque",
                            DateOfBirth = new DateTime(1991, 11, 3, 16, 36, 30, 774, DateTimeKind.Local).AddTicks(7296),
                            Email = "Herta.Lind73@hotmail.com",
                            FirstName = "Herta",
                            Gender = "Female",
                            HomePhone = "712-549-8074",
                            LastName = "Lind",
                            MiddleName = "Magnus",
                            WorkPhone = "772-533-8938"
                        },
                        new
                        {
                            Id = 138,
                            CellPhone = "909-792-0010",
                            CompanyName = "King, Littel and Pouros",
                            DateOfBirth = new DateTime(1965, 5, 29, 19, 27, 10, 479, DateTimeKind.Local).AddTicks(522),
                            Email = "Brayan.Legros21@gmail.com",
                            FirstName = "Brayan",
                            HomePhone = "248-583-9375",
                            LastName = "Legros",
                            MiddleName = "Celine"
                        },
                        new
                        {
                            Id = 139,
                            CellPhone = "336-217-9915",
                            CompanyName = "Batz - Emard",
                            DateOfBirth = new DateTime(1980, 8, 19, 6, 48, 54, 380, DateTimeKind.Local).AddTicks(1273),
                            Email = "Amir.Berge82@hotmail.com",
                            FirstName = "Amir",
                            HomePhone = "392-247-5995",
                            LastName = "Berge",
                            MiddleName = "Libbie"
                        },
                        new
                        {
                            Id = 140,
                            CellPhone = "268-827-1770",
                            CompanyName = "Rosenbaum, Fritsch and Parisian",
                            DateOfBirth = new DateTime(1995, 2, 8, 14, 19, 15, 574, DateTimeKind.Local).AddTicks(6050),
                            Email = "Ole_Mosciski6@hotmail.com",
                            FirstName = "Ole",
                            Gender = "Female",
                            LastName = "Mosciski",
                            MiddleName = "Marco",
                            WorkPhone = "598-611-2652"
                        },
                        new
                        {
                            Id = 141,
                            CellPhone = "212-350-3782",
                            CompanyName = "Ritchie, Walter and Kuhlman",
                            DateOfBirth = new DateTime(1993, 7, 29, 7, 51, 38, 635, DateTimeKind.Local).AddTicks(2118),
                            Email = "Demetris_Corwin@gmail.com",
                            FirstName = "Demetris",
                            LastName = "Corwin",
                            MiddleName = "Savannah",
                            WorkPhone = "526-689-1181"
                        },
                        new
                        {
                            Id = 142,
                            CompanyName = "Hackett LLC",
                            DateOfBirth = new DateTime(1974, 1, 17, 22, 36, 21, 772, DateTimeKind.Local).AddTicks(3850),
                            Email = "Aliyah.Lowe81@hotmail.com",
                            FirstName = "Aliyah",
                            Gender = "Male",
                            HomePhone = "386-756-2996",
                            LastName = "Lowe",
                            MiddleName = "Alena"
                        },
                        new
                        {
                            Id = 143,
                            CellPhone = "755-419-3867",
                            CompanyName = "Howe, Hammes and O'Kon",
                            DateOfBirth = new DateTime(1990, 3, 11, 18, 46, 16, 247, DateTimeKind.Local).AddTicks(252),
                            Email = "Adelia89@yahoo.com",
                            FirstName = "Adelia",
                            Gender = "Male",
                            LastName = "Kertzmann",
                            MiddleName = "Margarete",
                            WorkPhone = "433-733-0126"
                        },
                        new
                        {
                            Id = 144,
                            CompanyName = "Hirthe, Sipes and Orn",
                            DateOfBirth = new DateTime(1987, 10, 11, 0, 23, 25, 471, DateTimeKind.Local).AddTicks(5388),
                            Email = "Reese_Bashirian72@gmail.com",
                            FirstName = "Reese",
                            Gender = "Female",
                            LastName = "Bashirian",
                            MiddleName = "Elian"
                        },
                        new
                        {
                            Id = 145,
                            CompanyName = "Schmeler Inc",
                            DateOfBirth = new DateTime(1963, 7, 2, 18, 35, 27, 480, DateTimeKind.Local).AddTicks(7262),
                            Email = "Nella_Senger@hotmail.com",
                            FirstName = "Nella",
                            Gender = "Male",
                            LastName = "Senger",
                            MiddleName = "Jordi"
                        },
                        new
                        {
                            Id = 146,
                            CellPhone = "213-402-2897",
                            CompanyName = "Marvin LLC",
                            DateOfBirth = new DateTime(1973, 9, 6, 23, 16, 2, 356, DateTimeKind.Local).AddTicks(3215),
                            Email = "Miguel12@yahoo.com",
                            FirstName = "Miguel",
                            HomePhone = "303-726-4565",
                            LastName = "Kub",
                            MiddleName = "Tiara",
                            WorkPhone = "201-579-6354"
                        },
                        new
                        {
                            Id = 147,
                            CompanyName = "Schuppe Group",
                            DateOfBirth = new DateTime(1990, 6, 27, 11, 57, 30, 222, DateTimeKind.Local).AddTicks(7204),
                            Email = "Boyd.Price3@gmail.com",
                            FirstName = "Boyd",
                            Gender = "Female",
                            HomePhone = "871-952-3330",
                            LastName = "Price",
                            MiddleName = "Nathen",
                            WorkPhone = "453-348-9672"
                        },
                        new
                        {
                            Id = 148,
                            CompanyName = "Zboncak Inc",
                            DateOfBirth = new DateTime(1972, 1, 4, 8, 30, 34, 516, DateTimeKind.Local).AddTicks(4154),
                            Email = "Harold_Bartell71@hotmail.com",
                            FirstName = "Harold",
                            Gender = "Male",
                            HomePhone = "340-848-7435",
                            LastName = "Bartell",
                            MiddleName = "Ellen",
                            WorkPhone = "800-252-4077"
                        },
                        new
                        {
                            Id = 149,
                            CompanyName = "Rempel Inc",
                            DateOfBirth = new DateTime(1959, 9, 28, 14, 16, 8, 37, DateTimeKind.Local).AddTicks(5298),
                            Email = "Kara9@gmail.com",
                            FirstName = "Kara",
                            Gender = "Male",
                            HomePhone = "210-856-2908",
                            LastName = "Marquardt",
                            MiddleName = "Maybell",
                            WorkPhone = "505-210-1191"
                        },
                        new
                        {
                            Id = 150,
                            CompanyName = "Howell, Hand and Paucek",
                            DateOfBirth = new DateTime(1982, 3, 12, 4, 49, 40, 410, DateTimeKind.Local).AddTicks(30),
                            Email = "Jovan.Hackett@yahoo.com",
                            FirstName = "Jovan",
                            HomePhone = "634-353-7239",
                            LastName = "Hackett",
                            MiddleName = "Michale",
                            WorkPhone = "576-304-7188"
                        },
                        new
                        {
                            Id = 151,
                            CompanyName = "Oberbrunner, Dicki and Ebert",
                            DateOfBirth = new DateTime(1962, 6, 23, 4, 19, 40, 904, DateTimeKind.Local).AddTicks(3013),
                            Email = "Idella.Beatty@gmail.com",
                            FirstName = "Idella",
                            Gender = "Female",
                            LastName = "Beatty",
                            MiddleName = "Aimee"
                        },
                        new
                        {
                            Id = 152,
                            CellPhone = "249-629-5680",
                            CompanyName = "Gleichner Group",
                            DateOfBirth = new DateTime(1975, 12, 31, 0, 0, 21, 370, DateTimeKind.Local).AddTicks(1141),
                            Email = "Abbigail51@gmail.com",
                            FirstName = "Abbigail",
                            Gender = "Female",
                            HomePhone = "707-699-4986",
                            LastName = "Huel",
                            MiddleName = "Henry",
                            WorkPhone = "614-668-5162"
                        },
                        new
                        {
                            Id = 153,
                            CompanyName = "Monahan - Paucek",
                            DateOfBirth = new DateTime(1983, 4, 3, 13, 30, 4, 583, DateTimeKind.Local).AddTicks(5501),
                            Email = "Kendall.Rath99@gmail.com",
                            FirstName = "Kendall",
                            LastName = "Rath",
                            MiddleName = "Lilyan"
                        },
                        new
                        {
                            Id = 154,
                            CompanyName = "Dickinson, Ferry and Jacobs",
                            DateOfBirth = new DateTime(1995, 4, 13, 5, 7, 54, 29, DateTimeKind.Local).AddTicks(8802),
                            Email = "Idella26@yahoo.com",
                            FirstName = "Idella",
                            LastName = "Feil",
                            MiddleName = "Roger",
                            WorkPhone = "794-709-5557"
                        },
                        new
                        {
                            Id = 155,
                            CompanyName = "Steuber - Schneider",
                            DateOfBirth = new DateTime(1971, 4, 2, 13, 37, 19, 149, DateTimeKind.Local).AddTicks(4946),
                            Email = "Melvina_Friesen@gmail.com",
                            FirstName = "Melvina",
                            LastName = "Friesen",
                            MiddleName = "Harry"
                        },
                        new
                        {
                            Id = 156,
                            CompanyName = "Auer - Friesen",
                            DateOfBirth = new DateTime(1959, 9, 11, 20, 20, 10, 506, DateTimeKind.Local).AddTicks(9612),
                            Email = "Ron91@yahoo.com",
                            FirstName = "Ron",
                            LastName = "Doyle",
                            MiddleName = "Ezekiel"
                        },
                        new
                        {
                            Id = 157,
                            CompanyName = "Jaskolski - Flatley",
                            DateOfBirth = new DateTime(2002, 6, 23, 20, 39, 3, 149, DateTimeKind.Local).AddTicks(3426),
                            Email = "Colleen_Becker18@hotmail.com",
                            FirstName = "Colleen",
                            Gender = "Male",
                            HomePhone = "212-261-9875",
                            LastName = "Becker",
                            MiddleName = "Thaddeus"
                        },
                        new
                        {
                            Id = 158,
                            CellPhone = "364-810-7514",
                            CompanyName = "King, Marks and Wyman",
                            DateOfBirth = new DateTime(1991, 5, 23, 1, 11, 48, 926, DateTimeKind.Local).AddTicks(4100),
                            Email = "Howard_Krajcik30@yahoo.com",
                            FirstName = "Howard",
                            Gender = "Male",
                            HomePhone = "261-920-1277",
                            LastName = "Krajcik",
                            MiddleName = "Willy"
                        },
                        new
                        {
                            Id = 159,
                            CellPhone = "852-908-0525",
                            CompanyName = "Lesch, Kessler and Hettinger",
                            DateOfBirth = new DateTime(1980, 11, 1, 4, 45, 14, 899, DateTimeKind.Local).AddTicks(8580),
                            Email = "German.Conroy50@hotmail.com",
                            FirstName = "German",
                            HomePhone = "511-331-7672",
                            LastName = "Conroy",
                            MiddleName = "Leon"
                        },
                        new
                        {
                            Id = 160,
                            CompanyName = "Schimmel Inc",
                            DateOfBirth = new DateTime(1982, 8, 22, 5, 27, 36, 988, DateTimeKind.Local).AddTicks(7535),
                            Email = "Chesley.Hyatt59@hotmail.com",
                            FirstName = "Chesley",
                            HomePhone = "443-867-2091",
                            LastName = "Hyatt",
                            MiddleName = "Janae"
                        },
                        new
                        {
                            Id = 161,
                            CompanyName = "Sipes, Dibbert and King",
                            DateOfBirth = new DateTime(1976, 10, 24, 15, 13, 54, 563, DateTimeKind.Local).AddTicks(3714),
                            Email = "Jasen19@gmail.com",
                            FirstName = "Jasen",
                            Gender = "Male",
                            LastName = "Huels",
                            MiddleName = "Craig",
                            WorkPhone = "462-472-7110"
                        },
                        new
                        {
                            Id = 162,
                            CellPhone = "912-543-1936",
                            CompanyName = "Lemke - Schaefer",
                            DateOfBirth = new DateTime(1995, 8, 17, 17, 31, 1, 621, DateTimeKind.Local).AddTicks(3900),
                            Email = "Jeffrey_Osinski@hotmail.com",
                            FirstName = "Jeffrey",
                            Gender = "Male",
                            LastName = "Osinski",
                            MiddleName = "Darrick"
                        },
                        new
                        {
                            Id = 163,
                            CellPhone = "451-536-3123",
                            CompanyName = "Kulas Group",
                            DateOfBirth = new DateTime(1959, 5, 28, 16, 46, 37, 883, DateTimeKind.Local).AddTicks(4368),
                            Email = "Jerod44@hotmail.com",
                            FirstName = "Jerod",
                            LastName = "Hodkiewicz",
                            MiddleName = "Shea"
                        },
                        new
                        {
                            Id = 164,
                            CompanyName = "Rodriguez, Bosco and Kuhic",
                            DateOfBirth = new DateTime(1987, 1, 14, 17, 6, 45, 569, DateTimeKind.Local).AddTicks(7625),
                            Email = "Joshua.Lang85@yahoo.com",
                            FirstName = "Joshua",
                            Gender = "Female",
                            LastName = "Lang",
                            MiddleName = "Emile",
                            WorkPhone = "557-371-5927"
                        },
                        new
                        {
                            Id = 165,
                            CompanyName = "Stehr - Waters",
                            DateOfBirth = new DateTime(1980, 9, 18, 22, 9, 55, 855, DateTimeKind.Local).AddTicks(1011),
                            Email = "Virgil9@hotmail.com",
                            FirstName = "Virgil",
                            Gender = "Female",
                            LastName = "Green",
                            MiddleName = "Alanis",
                            WorkPhone = "973-809-4767"
                        },
                        new
                        {
                            Id = 166,
                            CellPhone = "544-274-7409",
                            CompanyName = "Koss - Bashirian",
                            DateOfBirth = new DateTime(1991, 7, 30, 20, 15, 40, 724, DateTimeKind.Local).AddTicks(1512),
                            Email = "Aimee26@yahoo.com",
                            FirstName = "Aimee",
                            Gender = "Female",
                            HomePhone = "422-835-1489",
                            LastName = "Davis",
                            MiddleName = "Pete"
                        },
                        new
                        {
                            Id = 167,
                            CellPhone = "469-394-2797",
                            CompanyName = "Dickinson - Wisoky",
                            DateOfBirth = new DateTime(1973, 2, 11, 12, 6, 27, 780, DateTimeKind.Local).AddTicks(8038),
                            Email = "Anabel.Stiedemann@yahoo.com",
                            FirstName = "Anabel",
                            Gender = "Female",
                            HomePhone = "956-247-7129",
                            LastName = "Stiedemann",
                            MiddleName = "Hollis",
                            WorkPhone = "534-494-8475"
                        },
                        new
                        {
                            Id = 168,
                            CellPhone = "814-636-4733",
                            CompanyName = "Hills, Glover and Hahn",
                            DateOfBirth = new DateTime(1966, 8, 16, 13, 55, 50, 76, DateTimeKind.Local).AddTicks(4255),
                            Email = "Ryann_Bernhard@yahoo.com",
                            FirstName = "Ryann",
                            Gender = "Female",
                            HomePhone = "457-660-8636",
                            LastName = "Bernhard",
                            MiddleName = "Kiarra",
                            WorkPhone = "488-580-4890"
                        },
                        new
                        {
                            Id = 169,
                            CellPhone = "560-867-7500",
                            CompanyName = "Keeling, Ward and Waelchi",
                            DateOfBirth = new DateTime(2002, 7, 21, 13, 7, 27, 183, DateTimeKind.Local).AddTicks(3063),
                            Email = "Darby_Kemmer90@yahoo.com",
                            FirstName = "Darby",
                            HomePhone = "869-580-5237",
                            LastName = "Kemmer",
                            MiddleName = "Pamela"
                        },
                        new
                        {
                            Id = 170,
                            CellPhone = "650-649-3734",
                            CompanyName = "Rau and Sons",
                            DateOfBirth = new DateTime(1999, 3, 29, 16, 47, 38, 218, DateTimeKind.Local).AddTicks(2771),
                            Email = "Garfield_Pfeffer70@gmail.com",
                            FirstName = "Garfield",
                            LastName = "Pfeffer",
                            MiddleName = "Bert",
                            WorkPhone = "675-384-7473"
                        },
                        new
                        {
                            Id = 171,
                            CellPhone = "530-847-9335",
                            CompanyName = "Fay, Roberts and Ledner",
                            DateOfBirth = new DateTime(1975, 4, 2, 15, 34, 5, 988, DateTimeKind.Local).AddTicks(8665),
                            Email = "Shea.Abernathy@gmail.com",
                            FirstName = "Shea",
                            LastName = "Abernathy",
                            MiddleName = "Aletha",
                            WorkPhone = "898-636-4213"
                        },
                        new
                        {
                            Id = 172,
                            CompanyName = "Gleason, Nolan and Morar",
                            DateOfBirth = new DateTime(2003, 7, 10, 6, 40, 46, 783, DateTimeKind.Local).AddTicks(2092),
                            Email = "Gust_Feest82@gmail.com",
                            FirstName = "Gust",
                            LastName = "Feest",
                            MiddleName = "Yvette"
                        },
                        new
                        {
                            Id = 173,
                            CompanyName = "Medhurst - Armstrong",
                            DateOfBirth = new DateTime(2003, 3, 25, 9, 38, 11, 400, DateTimeKind.Local).AddTicks(6025),
                            Email = "Beaulah_Schaefer23@gmail.com",
                            FirstName = "Beaulah",
                            HomePhone = "245-355-9933",
                            LastName = "Schaefer",
                            MiddleName = "Orville",
                            WorkPhone = "807-619-5391"
                        },
                        new
                        {
                            Id = 174,
                            CompanyName = "Hermiston Group",
                            DateOfBirth = new DateTime(1985, 6, 18, 19, 51, 54, 128, DateTimeKind.Local).AddTicks(4462),
                            Email = "Maxwell_Abbott@yahoo.com",
                            FirstName = "Maxwell",
                            HomePhone = "601-294-4114",
                            LastName = "Abbott",
                            MiddleName = "Jimmy"
                        },
                        new
                        {
                            Id = 175,
                            CellPhone = "532-355-7533",
                            CompanyName = "Wuckert - Waelchi",
                            DateOfBirth = new DateTime(2003, 12, 10, 0, 29, 6, 504, DateTimeKind.Local).AddTicks(7525),
                            Email = "Selmer38@hotmail.com",
                            FirstName = "Selmer",
                            Gender = "Female",
                            LastName = "Koss",
                            MiddleName = "Gene"
                        },
                        new
                        {
                            Id = 176,
                            CellPhone = "947-570-6853",
                            CompanyName = "Stokes and Sons",
                            DateOfBirth = new DateTime(1991, 2, 21, 13, 6, 21, 155, DateTimeKind.Local).AddTicks(4640),
                            Email = "Jaden46@yahoo.com",
                            FirstName = "Jaden",
                            HomePhone = "557-577-9884",
                            LastName = "Schroeder",
                            MiddleName = "Catherine"
                        },
                        new
                        {
                            Id = 177,
                            CompanyName = "Connelly - Howe",
                            DateOfBirth = new DateTime(1956, 6, 8, 11, 14, 16, 137, DateTimeKind.Local).AddTicks(8700),
                            Email = "Nora.Prohaska@gmail.com",
                            FirstName = "Nora",
                            Gender = "Male",
                            LastName = "Prohaska",
                            MiddleName = "Maeve",
                            WorkPhone = "789-576-1248"
                        },
                        new
                        {
                            Id = 178,
                            CellPhone = "275-661-8413",
                            CompanyName = "Quigley - Haley",
                            DateOfBirth = new DateTime(1977, 7, 6, 8, 53, 16, 39, DateTimeKind.Local).AddTicks(3595),
                            Email = "Lennie_Frami@gmail.com",
                            FirstName = "Lennie",
                            Gender = "Female",
                            LastName = "Frami",
                            MiddleName = "Cleve"
                        },
                        new
                        {
                            Id = 179,
                            CellPhone = "556-204-9513",
                            CompanyName = "Goldner - Schulist",
                            DateOfBirth = new DateTime(1991, 7, 25, 2, 29, 7, 347, DateTimeKind.Local).AddTicks(9201),
                            Email = "Sheridan_Wuckert5@gmail.com",
                            FirstName = "Sheridan",
                            Gender = "Female",
                            LastName = "Wuckert",
                            MiddleName = "Fritz",
                            WorkPhone = "877-476-7007"
                        },
                        new
                        {
                            Id = 180,
                            CompanyName = "Koepp - Weber",
                            DateOfBirth = new DateTime(1966, 4, 3, 9, 5, 41, 997, DateTimeKind.Local).AddTicks(8360),
                            Email = "Sherman.OConner32@gmail.com",
                            FirstName = "Sherman",
                            Gender = "Male",
                            LastName = "O'Conner",
                            MiddleName = "Kianna",
                            WorkPhone = "479-982-0429"
                        },
                        new
                        {
                            Id = 181,
                            CellPhone = "430-531-2023",
                            CompanyName = "Wiza, Becker and Hammes",
                            DateOfBirth = new DateTime(1998, 2, 8, 9, 16, 48, 394, DateTimeKind.Local).AddTicks(7673),
                            Email = "Nicholaus56@hotmail.com",
                            FirstName = "Nicholaus",
                            HomePhone = "253-895-4671",
                            LastName = "Bernier",
                            MiddleName = "Mertie",
                            WorkPhone = "797-670-9578"
                        },
                        new
                        {
                            Id = 182,
                            CompanyName = "Zboncak LLC",
                            DateOfBirth = new DateTime(1961, 5, 13, 9, 47, 19, 724, DateTimeKind.Local).AddTicks(7526),
                            Email = "Crystel.McDermott26@hotmail.com",
                            FirstName = "Crystel",
                            HomePhone = "622-743-1496",
                            LastName = "McDermott",
                            MiddleName = "Raphael"
                        },
                        new
                        {
                            Id = 183,
                            CompanyName = "Kreiger - Grady",
                            DateOfBirth = new DateTime(1969, 6, 21, 0, 25, 56, 740, DateTimeKind.Local).AddTicks(4337),
                            Email = "Salma.Parisian@yahoo.com",
                            FirstName = "Salma",
                            LastName = "Parisian",
                            MiddleName = "Kian",
                            WorkPhone = "939-611-9074"
                        },
                        new
                        {
                            Id = 184,
                            CompanyName = "Von, Cummings and Lebsack",
                            DateOfBirth = new DateTime(1984, 8, 29, 4, 42, 44, 650, DateTimeKind.Local).AddTicks(6798),
                            Email = "Reina_Simonis78@gmail.com",
                            FirstName = "Reina",
                            LastName = "Simonis",
                            MiddleName = "Jedediah"
                        },
                        new
                        {
                            Id = 185,
                            CellPhone = "553-287-0061",
                            CompanyName = "Hessel LLC",
                            DateOfBirth = new DateTime(1969, 8, 8, 19, 9, 18, 813, DateTimeKind.Local).AddTicks(3990),
                            Email = "Andy_Frami46@yahoo.com",
                            FirstName = "Andy",
                            Gender = "Female",
                            HomePhone = "745-864-2046",
                            LastName = "Frami",
                            MiddleName = "Arthur"
                        },
                        new
                        {
                            Id = 186,
                            CellPhone = "350-659-2484",
                            CompanyName = "Yundt Inc",
                            DateOfBirth = new DateTime(1972, 8, 30, 19, 41, 44, 984, DateTimeKind.Local).AddTicks(988),
                            Email = "Dameon.Bergnaum43@hotmail.com",
                            FirstName = "Dameon",
                            Gender = "Female",
                            HomePhone = "272-264-5675",
                            LastName = "Bergnaum",
                            MiddleName = "Aleen"
                        },
                        new
                        {
                            Id = 187,
                            CellPhone = "813-517-2417",
                            CompanyName = "Friesen, Fritsch and Abbott",
                            DateOfBirth = new DateTime(2002, 7, 2, 8, 1, 40, 268, DateTimeKind.Local).AddTicks(8102),
                            Email = "Pearline.Leuschke77@yahoo.com",
                            FirstName = "Pearline",
                            HomePhone = "895-823-9922",
                            LastName = "Leuschke",
                            MiddleName = "Crystal",
                            WorkPhone = "415-690-9567"
                        },
                        new
                        {
                            Id = 188,
                            CompanyName = "Wuckert Group",
                            DateOfBirth = new DateTime(1989, 1, 5, 14, 15, 30, 921, DateTimeKind.Local).AddTicks(3715),
                            Email = "Felix_Upton49@gmail.com",
                            FirstName = "Felix",
                            LastName = "Upton",
                            MiddleName = "Enos",
                            WorkPhone = "570-716-5921"
                        },
                        new
                        {
                            Id = 189,
                            CellPhone = "431-543-6587",
                            CompanyName = "Rippin, Legros and Ratke",
                            DateOfBirth = new DateTime(1991, 6, 4, 12, 30, 58, 69, DateTimeKind.Local).AddTicks(9813),
                            Email = "Lavina6@yahoo.com",
                            FirstName = "Lavina",
                            Gender = "Male",
                            LastName = "Rohan",
                            MiddleName = "Dariana"
                        },
                        new
                        {
                            Id = 190,
                            CompanyName = "O'Connell, Walsh and Stroman",
                            DateOfBirth = new DateTime(1972, 10, 20, 12, 3, 15, 100, DateTimeKind.Local).AddTicks(3685),
                            Email = "Wade28@gmail.com",
                            FirstName = "Wade",
                            Gender = "Female",
                            LastName = "Flatley",
                            MiddleName = "Jarret"
                        },
                        new
                        {
                            Id = 191,
                            CellPhone = "682-802-2481",
                            CompanyName = "Collins Group",
                            DateOfBirth = new DateTime(1963, 11, 4, 1, 39, 20, 490, DateTimeKind.Local).AddTicks(453),
                            Email = "Helga_Mann@hotmail.com",
                            FirstName = "Helga",
                            HomePhone = "912-971-9682",
                            LastName = "Mann",
                            MiddleName = "Price",
                            WorkPhone = "589-480-5668"
                        },
                        new
                        {
                            Id = 192,
                            CellPhone = "447-246-4241",
                            CompanyName = "Ankunding - Veum",
                            DateOfBirth = new DateTime(1970, 1, 30, 7, 59, 45, 61, DateTimeKind.Local).AddTicks(5719),
                            Email = "Kimberly.Medhurst0@hotmail.com",
                            FirstName = "Kimberly",
                            Gender = "Male",
                            HomePhone = "572-747-4828",
                            LastName = "Medhurst",
                            MiddleName = "Antwon",
                            WorkPhone = "901-513-4813"
                        },
                        new
                        {
                            Id = 193,
                            CellPhone = "691-982-3723",
                            CompanyName = "Larson Group",
                            DateOfBirth = new DateTime(1975, 8, 3, 16, 43, 9, 254, DateTimeKind.Local).AddTicks(435),
                            Email = "Olga89@yahoo.com",
                            FirstName = "Olga",
                            LastName = "Runolfsson",
                            MiddleName = "Adella",
                            WorkPhone = "816-813-9044"
                        },
                        new
                        {
                            Id = 194,
                            CellPhone = "955-953-9350",
                            CompanyName = "Johnson, Grant and Prohaska",
                            DateOfBirth = new DateTime(1956, 10, 6, 12, 22, 0, 819, DateTimeKind.Local).AddTicks(7887),
                            Email = "Dayna.Hoppe@yahoo.com",
                            FirstName = "Dayna",
                            Gender = "Female",
                            LastName = "Hoppe",
                            MiddleName = "Albina",
                            WorkPhone = "628-511-5240"
                        },
                        new
                        {
                            Id = 195,
                            CellPhone = "494-602-2305",
                            CompanyName = "Ward, Bins and Prosacco",
                            DateOfBirth = new DateTime(1978, 1, 2, 17, 59, 0, 521, DateTimeKind.Local).AddTicks(8774),
                            Email = "Billy_Wunsch80@yahoo.com",
                            FirstName = "Billy",
                            LastName = "Wunsch",
                            MiddleName = "Geoffrey"
                        },
                        new
                        {
                            Id = 196,
                            CellPhone = "847-833-5420",
                            CompanyName = "Bailey - Ankunding",
                            DateOfBirth = new DateTime(1969, 5, 15, 23, 1, 52, 440, DateTimeKind.Local).AddTicks(3439),
                            Email = "Stephan.Kulas@hotmail.com",
                            FirstName = "Stephan",
                            LastName = "Kulas",
                            MiddleName = "Tia"
                        },
                        new
                        {
                            Id = 197,
                            CompanyName = "Fay Group",
                            DateOfBirth = new DateTime(1975, 7, 14, 2, 51, 11, 413, DateTimeKind.Local).AddTicks(5290),
                            Email = "Celestino5@yahoo.com",
                            FirstName = "Celestino",
                            LastName = "Wiegand",
                            MiddleName = "Estell"
                        },
                        new
                        {
                            Id = 198,
                            CellPhone = "657-652-5595",
                            CompanyName = "Hegmann, Greenfelder and Greenholt",
                            DateOfBirth = new DateTime(1971, 4, 4, 17, 35, 57, 694, DateTimeKind.Local).AddTicks(792),
                            Email = "Elfrieda24@yahoo.com",
                            FirstName = "Elfrieda",
                            Gender = "Female",
                            HomePhone = "497-620-5677",
                            LastName = "Haley",
                            MiddleName = "Bradley"
                        },
                        new
                        {
                            Id = 199,
                            CellPhone = "970-891-3317",
                            CompanyName = "Raynor - Schowalter",
                            DateOfBirth = new DateTime(1961, 7, 25, 14, 3, 6, 832, DateTimeKind.Local).AddTicks(3017),
                            Email = "Gina36@yahoo.com",
                            FirstName = "Gina",
                            LastName = "Pouros",
                            MiddleName = "Leo"
                        },
                        new
                        {
                            Id = 200,
                            CompanyName = "Predovic Group",
                            DateOfBirth = new DateTime(1981, 2, 14, 23, 19, 56, 871, DateTimeKind.Local).AddTicks(2229),
                            Email = "Esther_Larson35@yahoo.com",
                            FirstName = "Esther",
                            LastName = "Larson",
                            MiddleName = "Juana",
                            WorkPhone = "914-302-7306"
                        });
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.Address", b =>
                {
                    b.HasOne("AddressBook.Api.Data.Entities.BookEntry", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.BookEntry", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
