/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackIcon: typeof import('./src/components/icons/BackIcon.vue')['default']
    CalendarIcon: typeof import('./src/components/icons/CalendarIcon.vue')['default']
    CartIcon: typeof import('./src/components/icons/CartIcon.vue')['default']
    CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
    CheckoutProgress: typeof import('./src/components/CheckoutProgress.vue')['default']
    ChevronLeftIcon: typeof import('./src/components/icons/ChevronLeftIcon.vue')['default']
    ChevronRightIcon: typeof import('./src/components/icons/ChevronRightIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    CreditCardIcon: typeof import('./src/components/icons/CreditCardIcon.vue')['default']
    DeleteIcon: typeof import('./src/components/icons/DeleteIcon.vue')['default']
    DoubleChevronIcon: typeof import('./src/components/icons/DoubleChevronIcon.vue')['default']
    EditIcon: typeof import('./src/components/icons/EditIcon.vue')['default']
    InfoIcon: typeof import('./src/components/icons/InfoIcon.vue')['default']
    Logo: typeof import('./src/components/icons/logo.vue')['default']
    LogoIcon: typeof import('./src/components/icons/LogoIcon.vue')['default']
    OrderDialog: typeof import('./src/components/OrderDialog.vue')['default']
    ProductModal: typeof import('./src/components/ProductModal.vue')['default']
    RightChevronIcon: typeof import('./src/components/icons/RightChevronIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZodError: typeof import('./src/components/ZodError.vue')['default']
  }
}
