// <auto-generated />
using System;
using BakeAndCake.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeAndCake.Api.Migrations
{
    [DbContext(typeof(BakeAndCakeDbContext))]
    [Migration("20260613212505_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.CustomPie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrustType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DedicationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryFilling")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("RequiredByDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomPies", (string)null);
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.CustomPieIngredient", b =>
                {
                    b.Property<int>("CustomPieId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CustomPieId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CustomPieIngredients", (string)null);
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLoyaltyMember")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_Email");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "margaret.whitfield@email.com",
                            FirstName = "Margaret",
                            IsLoyaltyMember = true,
                            LastName = "Whitfield",
                            LoyaltyPoints = 340,
                            Phone = "07700900001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robert.craine@email.com",
                            FirstName = "Robert",
                            IsLoyaltyMember = true,
                            LastName = "Craine",
                            LoyaltyPoints = 120,
                            Phone = "07700900002"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "saoirse.murphy@email.com",
                            FirstName = "Saoirse",
                            IsLoyaltyMember = false,
                            LastName = "Murphy",
                            LoyaltyPoints = 0
                        });
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllergenInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ReorderThreshold")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllergenInfo = "Gluten",
                            CostPerUnit = 0.0015m,
                            IsAllergen = true,
                            Name = "Plain Flour",
                            ReorderThreshold = 4000m,
                            StockQuantity = 20000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 2,
                            AllergenInfo = "Dairy",
                            CostPerUnit = 0.0120m,
                            IsAllergen = true,
                            Name = "Butter",
                            ReorderThreshold = 2000m,
                            StockQuantity = 10000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 3,
                            CostPerUnit = 0.0020m,
                            IsAllergen = false,
                            Name = "Caster Sugar",
                            ReorderThreshold = 3000m,
                            StockQuantity = 15000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 4,
                            AllergenInfo = "Eggs",
                            CostPerUnit = 0.3500m,
                            IsAllergen = true,
                            Name = "Free-Range Eggs",
                            ReorderThreshold = 60m,
                            StockQuantity = 300m,
                            Unit = "pc"
                        },
                        new
                        {
                            Id = 5,
                            AllergenInfo = "Dairy",
                            CostPerUnit = 0.0008m,
                            IsAllergen = true,
                            Name = "Whole Milk",
                            ReorderThreshold = 3000m,
                            StockQuantity = 15000m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 6,
                            AllergenInfo = "Dairy",
                            CostPerUnit = 0.0035m,
                            IsAllergen = true,
                            Name = "Double Cream",
                            ReorderThreshold = 1000m,
                            StockQuantity = 5000m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 7,
                            CostPerUnit = 0.0040m,
                            IsAllergen = false,
                            Name = "Bramley Apples",
                            ReorderThreshold = 2000m,
                            StockQuantity = 12000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 8,
                            CostPerUnit = 0.0120m,
                            IsAllergen = false,
                            Name = "Blackberries",
                            ReorderThreshold = 1000m,
                            StockQuantity = 5000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 9,
                            CostPerUnit = 0.0090m,
                            IsAllergen = false,
                            Name = "Cherry (pitted)",
                            ReorderThreshold = 1200m,
                            StockQuantity = 6000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 10,
                            CostPerUnit = 0.0180m,
                            IsAllergen = false,
                            Name = "Cocoa Powder",
                            ReorderThreshold = 600m,
                            StockQuantity = 3000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 11,
                            AllergenInfo = "May contain traces of nuts",
                            CostPerUnit = 0.0250m,
                            IsAllergen = true,
                            Name = "Dark Chocolate",
                            ReorderThreshold = 800m,
                            StockQuantity = 4000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 12,
                            CostPerUnit = 0.0110m,
                            IsAllergen = false,
                            Name = "Minced Beef",
                            ReorderThreshold = 1500m,
                            StockQuantity = 8000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 13,
                            CostPerUnit = 0.0095m,
                            IsAllergen = false,
                            Name = "Diced Chicken",
                            ReorderThreshold = 1500m,
                            StockQuantity = 8000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 14,
                            CostPerUnit = 0.0030m,
                            IsAllergen = false,
                            Name = "Leeks",
                            ReorderThreshold = 1000m,
                            StockQuantity = 5000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 15,
                            AllergenInfo = "Dairy",
                            CostPerUnit = 0.0140m,
                            IsAllergen = true,
                            Name = "Cheddar Cheese",
                            ReorderThreshold = 800m,
                            StockQuantity = 4000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 16,
                            CostPerUnit = 0.0025m,
                            IsAllergen = false,
                            Name = "Icing Sugar",
                            ReorderThreshold = 1000m,
                            StockQuantity = 5000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 17,
                            CostPerUnit = 0.0500m,
                            IsAllergen = false,
                            Name = "Vanilla Extract",
                            ReorderThreshold = 100m,
                            StockQuantity = 500m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 18,
                            CostPerUnit = 0.0050m,
                            IsAllergen = false,
                            Name = "Baking Powder",
                            ReorderThreshold = 400m,
                            StockQuantity = 2000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 19,
                            CostPerUnit = 0.0005m,
                            IsAllergen = false,
                            Name = "Salt",
                            ReorderThreshold = 500m,
                            StockQuantity = 5000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 20,
                            AllergenInfo = "Gluten, Dairy",
                            CostPerUnit = 1.2000m,
                            IsAllergen = true,
                            Name = "Puff Pastry Sheets",
                            ReorderThreshold = 20m,
                            StockQuantity = 100m,
                            Unit = "pc"
                        });
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Fulfilment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RequiredByDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderDate")
                        .HasDatabaseName("IX_Orders_OrderDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomPieId")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomPieId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllergyInformation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PreparationTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllergyInformation = "Contains Gluten, Dairy, Eggs",
                            Category = "Pie",
                            IsAvailable = true,
                            IsPieOfTheWeek = false,
                            Name = "Classic Apple Pie",
                            PreparationTimeMinutes = 60,
                            Price = 12.95m,
                            ShortDescription = "Old family recipe, Bramley apples & cinnamon"
                        },
                        new
                        {
                            Id = 2,
                            AllergyInformation = "Contains Gluten, Dairy, Eggs, Nuts",
                            Category = "Tart",
                            IsAvailable = true,
                            IsPieOfTheWeek = false,
                            Name = "Cherry & Almond Tart",
                            PreparationTimeMinutes = 45,
                            Price = 8.50m,
                            ShortDescription = "Sweet shortcrust with fresh cherries"
                        },
                        new
                        {
                            Id = 3,
                            AllergyInformation = "Contains Gluten, Dairy",
                            Category = "Pie",
                            IsAvailable = true,
                            IsPieOfTheWeek = true,
                            Name = "Steak & Ale Pie",
                            PreparationTimeMinutes = 90,
                            Price = 14.50m,
                            ShortDescription = "Slow-braised beef in rich ale gravy"
                        },
                        new
                        {
                            Id = 4,
                            AllergyInformation = "Contains Gluten, Dairy, Eggs",
                            Category = "Pie",
                            IsAvailable = true,
                            IsPieOfTheWeek = false,
                            Name = "Chicken, Leek & Cheese Pie",
                            PreparationTimeMinutes = 75,
                            Price = 13.00m,
                            ShortDescription = "Creamy filling with Cheddar top crust"
                        },
                        new
                        {
                            Id = 5,
                            AllergyInformation = "Contains Gluten, Dairy, Eggs",
                            Category = "Tart",
                            IsAvailable = true,
                            IsPieOfTheWeek = false,
                            Name = "Chocolate Silk Tart",
                            PreparationTimeMinutes = 50,
                            Price = 9.95m,
                            ShortDescription = "Dark chocolate ganache in a crisp shell"
                        },
                        new
                        {
                            Id = 6,
                            AllergyInformation = "Contains Gluten, Dairy",
                            Category = "Pie",
                            IsAvailable = true,
                            IsPieOfTheWeek = false,
                            Name = "Blackberry & Apple Crumble Pie",
                            PreparationTimeMinutes = 55,
                            Price = 11.50m,
                            ShortDescription = "Seasonal berries under a buttery crumble"
                        },
                        new
                        {
                            Id = 7,
                            AllergyInformation = "Contains Gluten, Dairy, Eggs",
                            Category = "Quiche",
                            IsAvailable = true,
                            IsPieOfTheWeek = false,
                            Name = "Cheese & Leek Quiche",
                            PreparationTimeMinutes = 50,
                            Price = 8.00m,
                            ShortDescription = "Savory custard with Cheddar & fresh leeks"
                        },
                        new
                        {
                            Id = 8,
                            AllergyInformation = "Contains Gluten, Dairy, Eggs",
                            Category = "Tart",
                            IsAvailable = true,
                            IsPieOfTheWeek = false,
                            Name = "Vanilla Custard Tart",
                            PreparationTimeMinutes = 40,
                            Price = 7.50m,
                            ShortDescription = "Silky-smooth custard in shortcrust pastry"
                        });
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityRequired")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IngredientId = 1,
                            QuantityRequired = 350m
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 2,
                            QuantityRequired = 175m
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 3,
                            QuantityRequired = 120m
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 4,
                            QuantityRequired = 2m
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 7,
                            QuantityRequired = 750m
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 1,
                            QuantityRequired = 300m
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 2,
                            QuantityRequired = 150m
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 12,
                            QuantityRequired = 600m
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 1,
                            QuantityRequired = 300m
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 2,
                            QuantityRequired = 150m
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 13,
                            QuantityRequired = 500m
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 14,
                            QuantityRequired = 200m
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 15,
                            QuantityRequired = 150m
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 1,
                            QuantityRequired = 200m
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 2,
                            QuantityRequired = 100m
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 11,
                            QuantityRequired = 300m
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 6,
                            QuantityRequired = 250m
                        });
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeGiven")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Receipts_ReceiptNumber");

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.CustomPie", b =>
                {
                    b.HasOne("BakeAndCake.Api.Data.Entities.Customer", "Customer")
                        .WithMany("CustomPies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.CustomPieIngredient", b =>
                {
                    b.HasOne("BakeAndCake.Api.Data.Entities.CustomPie", "CustomPie")
                        .WithMany("CustomPieIngredients")
                        .HasForeignKey("CustomPieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeAndCake.Api.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("CustomPieIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomPie");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Order", b =>
                {
                    b.HasOne("BakeAndCake.Api.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("BakeAndCake.Api.Data.Entities.CustomPie", "CustomPie")
                        .WithMany("OrderItems")
                        .HasForeignKey("CustomPieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BakeAndCake.Api.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeAndCake.Api.Data.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomPie");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.ProductIngredient", b =>
                {
                    b.HasOne("BakeAndCake.Api.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BakeAndCake.Api.Data.Entities.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Receipt", b =>
                {
                    b.HasOne("BakeAndCake.Api.Data.Entities.Order", "Order")
                        .WithOne("Receipt")
                        .HasForeignKey("BakeAndCake.Api.Data.Entities.Receipt", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.CustomPie", b =>
                {
                    b.Navigation("CustomPieIngredients");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Customer", b =>
                {
                    b.Navigation("CustomPies");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("CustomPieIngredients");

                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("BakeAndCake.Api.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
