// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewEfFeatures.Data;

#nullable disable

namespace NewEfFeatures.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20250116194933_Update1")]
    partial class Update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewEfFeatures.Data.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("FlightTime")
                        .HasColumnType("time");

                    b.Property<string>("Gate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Number" }, "IDX_FLIGHT_NUMBER");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex(new[] { "Number" }, "IDX_FLIGHT_NUMBER"), 80);

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Departure = new DateTime(2025, 2, 1, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "ATL",
                            DestinationAirport = "AMS",
                            FlightTime = new TimeSpan(0, 7, 30, 0, 0),
                            Number = "SW0074"
                        },
                        new
                        {
                            Id = 2,
                            Departure = new DateTime(2025, 2, 7, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "AMS",
                            DestinationAirport = "ATL",
                            FlightTime = new TimeSpan(0, 8, 30, 0, 0),
                            Number = "SW0075"
                        });
                });

            modelBuilder.Entity("NewEfFeatures.Data.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Boarded")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Boarded = true,
                            FirstName = "Shawn",
                            FlightId = 1,
                            LastName = "Wildermuth",
                            SeatNumber = "11B"
                        },
                        new
                        {
                            Id = 2,
                            Boarded = true,
                            FirstName = "Jim",
                            FlightId = 1,
                            LastName = "Smith",
                            SeatNumber = "31D"
                        },
                        new
                        {
                            Id = 3,
                            Boarded = true,
                            FirstName = "Rachel",
                            FlightId = 1,
                            LastName = "Moore",
                            SeatNumber = "19A"
                        },
                        new
                        {
                            Id = 4,
                            Boarded = false,
                            FirstName = "Shawn",
                            FlightId = 2,
                            LastName = "Wildermuth",
                            SeatNumber = "15F"
                        },
                        new
                        {
                            Id = 5,
                            Boarded = false,
                            FirstName = "Kelley",
                            FlightId = 2,
                            LastName = "Montegue",
                            SeatNumber = "2A"
                        });
                });

            modelBuilder.Entity("NewEfFeatures.Data.Passenger", b =>
                {
                    b.HasOne("NewEfFeatures.Data.Flight", null)
                        .WithMany("Passengers")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewEfFeatures.Data.Flight", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
