// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NewEfFeatures.Data.Optimized
{
    public partial class FlightContextModel
    {
        private FlightContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e72de13b-9270-4928-9eee-48a916c163a3"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var flight = FlightEntityType.Create(this);
            var passenger = PassengerEntityType.Create(this);

            PassengerEntityType.CreateForeignKey1(passenger, flight);

            FlightEntityType.CreateAnnotations(flight);
            PassengerEntityType.CreateAnnotations(passenger);

            AddAnnotation("ProductVersion", "9.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
