// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using NewEfFeatures.Data;
using NewEfFeatures.Data.Optimized;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(FlightContext), typeof(FlightContextModel))]
