// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SqlDev.Data;

#nullable disable

namespace DevSqlServer.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20250210011452_postgres")]
    partial class postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SqlDev.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("StateProvince")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "2125 Reynold Estate",
                            Address2 = "Apt. 962",
                            City = "New Katharinamouth",
                            PostalCode = "49786-9864",
                            StateProvince = "Wisconsin"
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "10025 Arjun Inlet",
                            City = "Lake Daronburgh",
                            PostalCode = "11664",
                            StateProvince = "Montana"
                        },
                        new
                        {
                            Id = 3,
                            Address1 = "448 Cara Flats",
                            Address2 = "Suite 286",
                            City = "Brendanfurt",
                            PostalCode = "06626",
                            StateProvince = "Iowa"
                        },
                        new
                        {
                            Id = 4,
                            Address1 = "969 Lang Expressway",
                            City = "Boyleburgh",
                            PostalCode = "99821-3638",
                            StateProvince = "Montana"
                        },
                        new
                        {
                            Id = 5,
                            Address1 = "213 Abernathy Shores",
                            Address2 = "Apt. 592",
                            City = "West Emiliaville",
                            PostalCode = "87195-9738",
                            StateProvince = "Wisconsin"
                        },
                        new
                        {
                            Id = 6,
                            Address1 = "170 Shaniya Stravenue",
                            City = "Rooseveltfort",
                            PostalCode = "08599",
                            StateProvince = "New Hampshire"
                        },
                        new
                        {
                            Id = 7,
                            Address1 = "9009 Altenwerth Radial",
                            City = "West Nicoburgh",
                            PostalCode = "78462",
                            StateProvince = "Illinois"
                        },
                        new
                        {
                            Id = 8,
                            Address1 = "42779 Lind Spurs",
                            City = "Jacobsonville",
                            PostalCode = "83659-2524",
                            StateProvince = "New Hampshire"
                        },
                        new
                        {
                            Id = 9,
                            Address1 = "3815 Shayna Spring",
                            Address2 = "Apt. 409",
                            City = "Lake Carlistad",
                            PostalCode = "53697",
                            StateProvince = "Delaware"
                        },
                        new
                        {
                            Id = 10,
                            Address1 = "58924 Ila Neck",
                            Address2 = "Apt. 033",
                            City = "New Sonnyshire",
                            PostalCode = "95468-6409",
                            StateProvince = "California"
                        },
                        new
                        {
                            Id = 11,
                            Address1 = "236 Austyn Junctions",
                            Address2 = "Suite 660",
                            City = "Lake Philip",
                            PostalCode = "30846",
                            StateProvince = "Rhode Island"
                        },
                        new
                        {
                            Id = 12,
                            Address1 = "779 Jayne Wells",
                            City = "Greenholtshire",
                            PostalCode = "99347-2268",
                            StateProvince = "Nebraska"
                        },
                        new
                        {
                            Id = 13,
                            Address1 = "5241 Annabelle Brook",
                            City = "Chaddville",
                            PostalCode = "30428-2843",
                            StateProvince = "Maryland"
                        },
                        new
                        {
                            Id = 14,
                            Address1 = "96538 Destinee Heights",
                            City = "Lake Giuseppeton",
                            PostalCode = "36833-8512",
                            StateProvince = "Ohio"
                        },
                        new
                        {
                            Id = 15,
                            Address1 = "96509 Tod Common",
                            City = "Corwinfurt",
                            PostalCode = "08877",
                            StateProvince = "Kentucky"
                        },
                        new
                        {
                            Id = 16,
                            Address1 = "0030 Shaina Alley",
                            City = "West Clarkborough",
                            PostalCode = "34274",
                            StateProvince = "California"
                        },
                        new
                        {
                            Id = 17,
                            Address1 = "03210 Tina Extensions",
                            Address2 = "Apt. 260",
                            City = "Rhiannonmouth",
                            PostalCode = "18318-8577",
                            StateProvince = "Louisiana"
                        },
                        new
                        {
                            Id = 18,
                            Address1 = "8874 Maximillia Lane",
                            City = "Lake Caramouth",
                            PostalCode = "55798",
                            StateProvince = "Illinois"
                        },
                        new
                        {
                            Id = 19,
                            Address1 = "34557 Bradtke Cove",
                            City = "Lake Franciscahaven",
                            PostalCode = "58146",
                            StateProvince = "Louisiana"
                        },
                        new
                        {
                            Id = 20,
                            Address1 = "82805 Emard Terrace",
                            City = "Port Efren",
                            PostalCode = "62017-1868",
                            StateProvince = "Ohio"
                        },
                        new
                        {
                            Id = 21,
                            Address1 = "9293 Orn Lodge",
                            City = "Wilhelmton",
                            PostalCode = "86554",
                            StateProvince = "Alabama"
                        },
                        new
                        {
                            Id = 22,
                            Address1 = "46060 Devon Mall",
                            Address2 = "Apt. 040",
                            City = "Dorthyborough",
                            PostalCode = "06912",
                            StateProvince = "North Carolina"
                        },
                        new
                        {
                            Id = 23,
                            Address1 = "1291 Jerad Shoal",
                            Address2 = "Suite 489",
                            City = "Fritschfurt",
                            PostalCode = "86501-7539",
                            StateProvince = "Idaho"
                        },
                        new
                        {
                            Id = 24,
                            Address1 = "9385 Aurelia Unions",
                            City = "East Jaiden",
                            PostalCode = "87133",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 25,
                            Address1 = "07172 Moen Pines",
                            Address2 = "Suite 643",
                            City = "Crookston",
                            PostalCode = "27751",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 26,
                            Address1 = "101 Dixie Oval",
                            Address2 = "Suite 763",
                            City = "South Nataliemouth",
                            PostalCode = "26717-3673",
                            StateProvince = "Delaware"
                        },
                        new
                        {
                            Id = 27,
                            Address1 = "47378 Leffler Center",
                            Address2 = "Apt. 175",
                            City = "Florinefurt",
                            PostalCode = "24559-2405",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 28,
                            Address1 = "972 Koelpin Ranch",
                            City = "Terryshire",
                            PostalCode = "12536-2817",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 29,
                            Address1 = "785 Rutherford Views",
                            Address2 = "Suite 360",
                            City = "Haleyburgh",
                            PostalCode = "40466",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 30,
                            Address1 = "826 Raven Village",
                            City = "Johnathanbury",
                            PostalCode = "49604",
                            StateProvince = "New York"
                        },
                        new
                        {
                            Id = 31,
                            Address1 = "1303 Bonita Grove",
                            Address2 = "Suite 320",
                            City = "Strosinfurt",
                            PostalCode = "05450-7878",
                            StateProvince = "Ohio"
                        },
                        new
                        {
                            Id = 32,
                            Address1 = "283 Wunsch Glen",
                            City = "Lake Demond",
                            PostalCode = "47648",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 33,
                            Address1 = "82344 VonRueden Course",
                            City = "Rowefort",
                            PostalCode = "97181",
                            StateProvince = "New Hampshire"
                        },
                        new
                        {
                            Id = 34,
                            Address1 = "91214 Imelda Isle",
                            Address2 = "Suite 336",
                            City = "West Joshua",
                            PostalCode = "04053-7902",
                            StateProvince = "Connecticut"
                        },
                        new
                        {
                            Id = 35,
                            Address1 = "5509 Cremin Spur",
                            City = "Jacobsonfurt",
                            PostalCode = "07519",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 36,
                            Address1 = "16900 Elton Ramp",
                            Address2 = "Apt. 901",
                            City = "Port Isabelbury",
                            PostalCode = "29321-6380",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 37,
                            Address1 = "74238 Theo Avenue",
                            Address2 = "Apt. 430",
                            City = "Heathcoteport",
                            PostalCode = "02173-8070",
                            StateProvince = "Texas"
                        },
                        new
                        {
                            Id = 38,
                            Address1 = "5961 Antwon Burgs",
                            City = "Aldenville",
                            PostalCode = "44714-9921",
                            StateProvince = "West Virginia"
                        },
                        new
                        {
                            Id = 39,
                            Address1 = "1730 Lolita Plaza",
                            City = "West Wilfredland",
                            PostalCode = "57191",
                            StateProvince = "Kansas"
                        },
                        new
                        {
                            Id = 40,
                            Address1 = "002 Gislason Trafficway",
                            City = "New Elyseville",
                            PostalCode = "64415-8486",
                            StateProvince = "West Virginia"
                        },
                        new
                        {
                            Id = 41,
                            Address1 = "5249 Keebler Fall",
                            City = "East Makaylaburgh",
                            PostalCode = "78474-2694",
                            StateProvince = "Pennsylvania"
                        },
                        new
                        {
                            Id = 42,
                            Address1 = "2211 Dessie Key",
                            City = "Lake Guillermoview",
                            PostalCode = "99578",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 43,
                            Address1 = "98397 Arlo Wells",
                            City = "Ankundingmouth",
                            PostalCode = "05530",
                            StateProvince = "Mississippi"
                        },
                        new
                        {
                            Id = 44,
                            Address1 = "386 O'Hara Mill",
                            City = "Port Sincerestad",
                            PostalCode = "39351-3930",
                            StateProvince = "Connecticut"
                        },
                        new
                        {
                            Id = 45,
                            Address1 = "091 Laurine Street",
                            Address2 = "Apt. 644",
                            City = "New Guillermoside",
                            PostalCode = "45154-0916",
                            StateProvince = "Texas"
                        },
                        new
                        {
                            Id = 46,
                            Address1 = "79604 Joyce Walks",
                            Address2 = "Apt. 017",
                            City = "O'Konland",
                            PostalCode = "61250-9452",
                            StateProvince = "Nebraska"
                        },
                        new
                        {
                            Id = 47,
                            Address1 = "8939 West Garden",
                            City = "New Scottie",
                            PostalCode = "55784-3000",
                            StateProvince = "Iowa"
                        },
                        new
                        {
                            Id = 48,
                            Address1 = "4193 Ebony Hills",
                            Address2 = "Apt. 895",
                            City = "Madisonview",
                            PostalCode = "88816-6061",
                            StateProvince = "Missouri"
                        },
                        new
                        {
                            Id = 49,
                            Address1 = "9544 Friesen Stravenue",
                            Address2 = "Suite 951",
                            City = "Lake Gussie",
                            PostalCode = "00298-3129",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 50,
                            Address1 = "0285 Hammes Shoals",
                            City = "New Kelvin",
                            PostalCode = "36428-0604",
                            StateProvince = "Arkansas"
                        });
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CompanyName = "Macejkovic - Blanda",
                            ContactName = "Reynold Davis",
                            Phone = "425-339-6282"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CompanyName = "Ryan - Wolff",
                            ContactName = "Minnie Kessler"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            CompanyName = "Herman Inc",
                            ContactName = "Austin Beatty",
                            Phone = "490-676-0072"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            CompanyName = "Koepp - Cummings",
                            ContactName = "Caleb Moen",
                            Phone = "747-511-2448"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 5,
                            CompanyName = "Schulist LLC",
                            ContactName = "Sasha Pagac",
                            Phone = "322-706-6268"
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 6,
                            CompanyName = "Lang, Dickens and White",
                            ContactName = "Manuela Wiegand",
                            Phone = "597-528-0356"
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 7,
                            CompanyName = "Stamm, Ernser and Cronin",
                            ContactName = "Francesca Murazik",
                            Phone = "489-850-7213"
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 8,
                            CompanyName = "Welch - Frami",
                            ContactName = "Stephanie Blanda",
                            Phone = "419-498-7195"
                        },
                        new
                        {
                            Id = 9,
                            AddressId = 9,
                            CompanyName = "Haag, Senger and Nienow",
                            ContactName = "Myron Herzog",
                            Phone = "917-809-4141"
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 10,
                            CompanyName = "Schmitt, Mann and Johnston",
                            ContactName = "Abbie Stokes"
                        },
                        new
                        {
                            Id = 11,
                            AddressId = 11,
                            CompanyName = "VonRueden, Gutmann and Parker",
                            ContactName = "Josefina Cormier",
                            Phone = "272-524-7846"
                        },
                        new
                        {
                            Id = 12,
                            AddressId = 12,
                            CompanyName = "Cartwright - Welch",
                            ContactName = "Kale Sawayn",
                            Phone = "577-492-2110"
                        },
                        new
                        {
                            Id = 13,
                            AddressId = 13,
                            CompanyName = "D'Amore - Mann",
                            ContactName = "Santino Streich",
                            Phone = "459-725-2425"
                        },
                        new
                        {
                            Id = 14,
                            AddressId = 14,
                            CompanyName = "Runolfsdottir, Haley and Stracke",
                            ContactName = "Brionna Lang",
                            Phone = "309-571-8161"
                        },
                        new
                        {
                            Id = 15,
                            AddressId = 15,
                            CompanyName = "Hagenes - O'Connell",
                            ContactName = "Terrence Schamberger",
                            Phone = "544-255-8924"
                        },
                        new
                        {
                            Id = 16,
                            AddressId = 16,
                            CompanyName = "Howell and Sons",
                            ContactName = "Randall Dibbert",
                            Phone = "790-989-5468"
                        },
                        new
                        {
                            Id = 17,
                            AddressId = 17,
                            CompanyName = "Bogan - Veum",
                            ContactName = "Whitney Ward",
                            Phone = "432-236-9660"
                        },
                        new
                        {
                            Id = 18,
                            AddressId = 18,
                            CompanyName = "Schmidt Group",
                            ContactName = "Oda Frami",
                            Phone = "484-268-9449"
                        },
                        new
                        {
                            Id = 19,
                            AddressId = 19,
                            CompanyName = "Upton, Kerluke and Trantow",
                            ContactName = "Eriberto Kreiger",
                            Phone = "529-857-9934"
                        },
                        new
                        {
                            Id = 20,
                            AddressId = 20,
                            CompanyName = "Fahey LLC",
                            ContactName = "Sallie Bergstrom",
                            Phone = "500-252-4197"
                        },
                        new
                        {
                            Id = 21,
                            AddressId = 21,
                            CompanyName = "Funk, Rodriguez and D'Amore",
                            ContactName = "Carmela Howe",
                            Phone = "804-428-2843"
                        },
                        new
                        {
                            Id = 22,
                            AddressId = 22,
                            CompanyName = "Gaylord and Sons",
                            ContactName = "Erin VonRueden",
                            Phone = "738-639-1310"
                        },
                        new
                        {
                            Id = 23,
                            AddressId = 23,
                            CompanyName = "Block - Parker",
                            ContactName = "Kurt Hagenes"
                        },
                        new
                        {
                            Id = 24,
                            AddressId = 24,
                            CompanyName = "Borer, Wuckert and Osinski",
                            ContactName = "Kamille Bernier",
                            Phone = "928-630-9163"
                        },
                        new
                        {
                            Id = 25,
                            AddressId = 25,
                            CompanyName = "Smith Group",
                            ContactName = "Pietro Rohan",
                            Phone = "248-600-0309"
                        },
                        new
                        {
                            Id = 26,
                            AddressId = 26,
                            CompanyName = "Gibson, Gislason and Cummings",
                            ContactName = "Gilberto Dicki",
                            Phone = "403-242-7411"
                        },
                        new
                        {
                            Id = 27,
                            AddressId = 27,
                            CompanyName = "Donnelly, Abernathy and Gutkowski",
                            ContactName = "Edgardo Davis",
                            Phone = "226-509-5873"
                        },
                        new
                        {
                            Id = 28,
                            AddressId = 28,
                            CompanyName = "Towne and Sons",
                            ContactName = "Carolina Schroeder",
                            Phone = "977-635-2648"
                        },
                        new
                        {
                            Id = 29,
                            AddressId = 29,
                            CompanyName = "Konopelski, Stroman and Yost",
                            ContactName = "Shany Little",
                            Phone = "271-352-1557"
                        },
                        new
                        {
                            Id = 30,
                            AddressId = 30,
                            CompanyName = "Hegmann, Green and Schmidt",
                            ContactName = "Baron Carroll"
                        },
                        new
                        {
                            Id = 31,
                            AddressId = 31,
                            CompanyName = "Hettinger, Trantow and Hermann",
                            ContactName = "Adrien Macejkovic",
                            Phone = "846-332-5288"
                        },
                        new
                        {
                            Id = 32,
                            AddressId = 32,
                            CompanyName = "Boehm, Lesch and Blanda",
                            ContactName = "Martina Heidenreich"
                        },
                        new
                        {
                            Id = 33,
                            AddressId = 33,
                            CompanyName = "Dach, Shields and Mills",
                            ContactName = "Reuben Schaefer",
                            Phone = "564-692-9396"
                        },
                        new
                        {
                            Id = 34,
                            AddressId = 34,
                            CompanyName = "Corkery, Ratke and Wuckert",
                            ContactName = "Armand Armstrong",
                            Phone = "465-854-9002"
                        },
                        new
                        {
                            Id = 35,
                            AddressId = 35,
                            CompanyName = "Pfannerstill - Abernathy",
                            ContactName = "Marley Barton"
                        },
                        new
                        {
                            Id = 36,
                            AddressId = 36,
                            CompanyName = "Welch - Cormier",
                            ContactName = "Effie Casper",
                            Phone = "747-312-9174"
                        },
                        new
                        {
                            Id = 37,
                            AddressId = 37,
                            CompanyName = "Langworth, Swaniawski and Fritsch",
                            ContactName = "Margot Farrell",
                            Phone = "765-801-7539"
                        },
                        new
                        {
                            Id = 38,
                            AddressId = 38,
                            CompanyName = "Green - Botsford",
                            ContactName = "Tara Witting",
                            Phone = "455-899-0032"
                        },
                        new
                        {
                            Id = 39,
                            AddressId = 39,
                            CompanyName = "Haley, Schultz and Runte",
                            ContactName = "Beatrice Heidenreich",
                            Phone = "526-466-0717"
                        },
                        new
                        {
                            Id = 40,
                            AddressId = 40,
                            CompanyName = "O'Kon, Krajcik and Harris",
                            ContactName = "Waylon Zboncak",
                            Phone = "371-227-7518"
                        },
                        new
                        {
                            Id = 41,
                            AddressId = 41,
                            CompanyName = "Gleichner LLC",
                            ContactName = "Carson Beer",
                            Phone = "276-937-2577"
                        },
                        new
                        {
                            Id = 42,
                            AddressId = 42,
                            CompanyName = "Grant, Paucek and Sauer",
                            ContactName = "Brayan Rohan",
                            Phone = "473-711-5504"
                        },
                        new
                        {
                            Id = 43,
                            AddressId = 43,
                            CompanyName = "Runolfsson - Treutel",
                            ContactName = "Colleen Cartwright",
                            Phone = "755-636-4824"
                        },
                        new
                        {
                            Id = 44,
                            AddressId = 44,
                            CompanyName = "Wolf - Grant",
                            ContactName = "Jennings Bahringer",
                            Phone = "699-446-9720"
                        },
                        new
                        {
                            Id = 45,
                            AddressId = 45,
                            CompanyName = "Jakubowski Inc",
                            ContactName = "Wilford Terry",
                            Phone = "951-725-3628"
                        },
                        new
                        {
                            Id = 46,
                            AddressId = 46,
                            CompanyName = "McLaughlin, Yost and Lubowitz",
                            ContactName = "Oliver Weimann",
                            Phone = "859-836-0673"
                        },
                        new
                        {
                            Id = 47,
                            AddressId = 47,
                            CompanyName = "Brakus - Klocko",
                            ContactName = "Antone Kiehn",
                            Phone = "727-738-9826"
                        },
                        new
                        {
                            Id = 48,
                            AddressId = 48,
                            CompanyName = "Cummings - Durgan",
                            ContactName = "Dax Lind",
                            Phone = "663-549-6045"
                        },
                        new
                        {
                            Id = 49,
                            AddressId = 49,
                            CompanyName = "Cartwright and Sons",
                            ContactName = "Brianne Howell",
                            Phone = "293-420-5986"
                        },
                        new
                        {
                            Id = 50,
                            AddressId = 50,
                            CompanyName = "Bayer - Luettgen",
                            ContactName = "Hulda Marks",
                            Phone = "287-787-9792"
                        });
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Customer", b =>
                {
                    b.HasOne("SqlDev.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Order", b =>
                {
                    b.HasOne("SqlDev.Data.Entities.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlDev.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("SqlDev.Data.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SqlDev.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
